project:
  type: website
  output-dir: docs

website:
  title: "Michele Andreozzi | CFD Portfolio"
  favicon: assets/logo.svg
  site-url: "https://github.com/andreozzimichele/1d23982d-7cc9-46d9-8530-f6d58455ad62"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: 2026 Rear Wing Study
        
format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    fig-align: center
    html-math-method: mathjax
    include-in-header: hide-from-google.html
