<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michele Andreozzi">
<meta name="dcterms.date" content="2026-03-25">

<title>2026 Formula 1 Rear Wing Development – Michele Andreozzi | CFD Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./assets/logo.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1c06a759423a8071d2c369b265bd9085.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e3b669efb3ef36c2dd059066fb764b00.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Michele Andreozzi | CFD Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">2026 Rear Wing Study</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> 1. Introduction</a>
  <ul class="collapse">
  <li><a href="#a-much-needed-disclaimer" id="toc-a-much-needed-disclaimer" class="nav-link" data-scroll-target="#a-much-needed-disclaimer"><span class="header-section-number">1.1</span> 1.1 A Much Needed Disclaimer</a></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="header-section-number">2</span> 2. Methodology</a>
  <ul class="collapse">
  <li><a href="#hardware" id="toc-hardware" class="nav-link" data-scroll-target="#hardware"><span class="header-section-number">2.1</span> 2.1 Hardware</a></li>
  <li><a href="#geometry" id="toc-geometry" class="nav-link" data-scroll-target="#geometry"><span class="header-section-number">2.2</span> 2.2 Geometry</a></li>
  <li><a href="#a-note-on-automation" id="toc-a-note-on-automation" class="nav-link" data-scroll-target="#a-note-on-automation"><span class="header-section-number">2.3</span> 2.3 A Note on Automation</a></li>
  <li><a href="#meshing" id="toc-meshing" class="nav-link" data-scroll-target="#meshing"><span class="header-section-number">2.4</span> 2.4 Meshing</a></li>
  <li><a href="#physics-numerics" id="toc-physics-numerics" class="nav-link" data-scroll-target="#physics-numerics"><span class="header-section-number">2.5</span> 2.5 Physics &amp; Numerics</a></li>
  <li><a href="#grid-convergence-study" id="toc-grid-convergence-study" class="nav-link" data-scroll-target="#grid-convergence-study"><span class="header-section-number">2.6</span> 2.6 Grid Convergence Study</a></li>
  <li><a href="#post-processing" id="toc-post-processing" class="nav-link" data-scroll-target="#post-processing"><span class="header-section-number">2.7</span> 2.7 Post-Processing</a></li>
  </ul></li>
  <li><a href="#results-and-discussion" id="toc-results-and-discussion" class="nav-link" data-scroll-target="#results-and-discussion"><span class="header-section-number">3</span> 3. Results and Discussion</a>
  <ul class="collapse">
  <li><a href="#initial-results" id="toc-initial-results" class="nav-link" data-scroll-target="#initial-results"><span class="header-section-number">3.1</span> 3.1 Initial results</a></li>
  <li><a href="#design-evolution" id="toc-design-evolution" class="nav-link" data-scroll-target="#design-evolution"><span class="header-section-number">3.2</span> 3.2 Design Evolution</a></li>
  <li><a href="#straight-line-mode-slm-configurations" id="toc-straight-line-mode-slm-configurations" class="nav-link" data-scroll-target="#straight-line-mode-slm-configurations"><span class="header-section-number">3.3</span> 3.3 Straight Line Mode (SLM) Configurations</a></li>
  <li><a href="#a-final-discussion-on-grid-convergence" id="toc-a-final-discussion-on-grid-convergence" class="nav-link" data-scroll-target="#a-final-discussion-on-grid-convergence"><span class="header-section-number">3.4</span> 3.4 A Final Discussion on Grid Convergence</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">4</span> 4. Conclusions</a></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements"><span class="header-section-number">5</span> Acknowledgements</a></li>
  <li><a href="#appendix-code-automation-example" id="toc-appendix-code-automation-example" class="nav-link" data-scroll-target="#appendix-code-automation-example"><span class="header-section-number">6</span> Appendix: Code Automation Example</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2026 Formula 1 Rear Wing Development</h1>
<p class="subtitle lead">CFD Simulation Study</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michele Andreozzi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Abstract
</div>
</div>
<div class="callout-body-container callout-body">
<p>This report presents the aerodynamic development of a 2026 Formula 1 rear wing using Computational Fluid Dynamics simulations. Fourteen different geometries were investigated using OpenFOAM, evaluating lift coefficient, drag coefficient, lift-to-drag ratio, and field values analysis, such as pressure coefficient and wall bounded streamlines. The study intends to both evaluate the usage of CFD as a reliable method for aerodynamic performance prediction and to also prove a broad understanding of the current F1 ruleset regarding the rear wing.</p>
</div>
</div>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> 1. Introduction</h2>
<p>The 2026 Formula 1 regulations introduce significant changes to rear wing design: traditional endplates are brought back, but a very tight RV-RW-PROFILES reference volume is introduced, and the evolution from DRS to SLM for straight line drag reduction forces aerodynamic engineers to explore new development paths.</p>
<p>This study is developed in 3 major stages:</p>
<ul>
<li>A mesh convergence analysis, using the Grid Convergence Index as the main metric to evaluate different meshes.</li>
<li>A series of geometry evolutions aimed at achieving high downforce and reducing undesirable effects such as separations.</li>
<li>An investigation into different Straight Line Mode options for hinge positioning and movement of the flaps.</li>
</ul>
<section id="a-much-needed-disclaimer" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="a-much-needed-disclaimer"><span class="header-section-number">1.1</span> 1.1 A Much Needed Disclaimer</h3>
<p>While hopefully not needed, in the sense that everybody reading this should know it already, I’d rather be safe than sorry and clearly state the not so obvious: aerodynamics is governed by the Navier-Stokes equations, which are known for their mathematical complexity. The equations are nonlinear, and in their incompressible version they describe a situation that shows many similarities with a purely <a href="https://cfd.university/learn/10-key-concepts-everyone-must-understand-in-cfd/what-are-hyperbolic-parabolic-and-elliptic-equations-in-cfd">elliptic</a> problem, i.e.&nbsp;one where all points in the domain influence each other, both upstream and downstream. Moreover F1 cars are extremely complex pieces of technology, where the amount of detail is extraordinary with respect to all aspects of engineering. These two statements should make it clear that:</p>
<ul>
<li>Correctly modelling an F1 car through CFD is no trivial task. Every assumption should be double (or even triple) checked, as each introduces small deviations from reality that might catastrophically lead to a result that significantly diverges from the one found on track. While indubitably colorful, CFD should always be treated with immense care and some well informed suspicion</li>
<li>Even if the perfect CFD recipe for F1 existed (more than highly unlikely), applying it only to the simulation of the rear wing is not going to give the full picture. The rear wing is placed downstream of a number of aerodynamic components, each working air in a specific way: as such the incoming flow is surely not aligned with the <span class="math inline">\(x\)</span> axis and vorticity shed by the front wing, turning vanes and all series of detailing that modern F1 cars are full of is going to produce a number of vortices that guide engineers in the design of the rear end. Moreover the rear wing interacts heavily with the diffuser and the rear suspension, helping extract maximum downforce from the floor</li>
</ul>
<p>The conclusion in simple: the results in this report are clearly not meant to uncover the real numbers that F1 teams see in their CFD sims or in the wind tunnel. It is a learning project, aimed more at understanding why some design choices are made and how engineers might find performance in a component as crucial as the rear wing. The reader, possibly at the end of each paragraph, should ask himself: what are the possible inaccuracies stemming from what was just explained? Why would an aerodynamicist take a specific development path in this case? Is the picture clear from a methodology perspective? Reading CFD numbers (and aero numbers in general) without a critical eye is the best way to get trapped in misleading explanations and consequently ineffective solutions.</p>
<hr>
</section>
</section>
<section id="methodology" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="methodology"><span class="header-section-number">2</span> 2. Methodology</h2>
<section id="hardware" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="hardware"><span class="header-section-number">2.1</span> 2.1 Hardware</h3>
<p>All simulations were conducted using precompiled OpenFOAM ESI (version v2506) on personal hardware, which provided limited specs:</p>
<ul>
<li>4 physical Intel Core i7-8565U, with possibility of dual threading for a total 8 vCPU (not suggested for CFD usage)</li>
<li>a 16 GB DDR4 random access memory stick</li>
<li>512 GB of SSD storage, providing faster I/O during simulations</li>
<li>1 TB of HDD storage, for long term storage of simulation results</li>
</ul>
<p>On a machine running Debian 13 as the OS, to strip down the system of all unnecessary software and provide good responsiveness. This hardware configuration is nonetheless very limited for CFD, where ideally one would have about 250,000 cells per core, and no more than 1 million cells per GB of memory. The PC can be thus estimated to hit a mesh size limit at about 8 million cells (considering OS and all processes taking place alongside the pure computation) before being trapped in OOM errors, but would provide results for such grid in a painfully slow turnaround time. Not having access to more capable hardware forced the choice to a compromise in terms of accuracy, which will soon be discussed. Limits of the machine will be dealt with again in a later section.</p>
<p>For all of the above reasons it was decided that the simulations would be run as an incompressible steady state symmetric cases about the <span class="math inline">\(y=0\)</span> plane (as mentioned above the hardware limitations where really stringent, so the known limitations of a symmetric simulation were significantly outnumbered by the gained accuracy through a mesh twice as fine).</p>
</section>
<section id="geometry" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="geometry"><span class="header-section-number">2.2</span> 2.2 Geometry</h3>
<p>The rear wing geometry consists of a multi-element configuration stored in STL format (<code>rearWing.stl</code>). The geometry was built completely from scratch using the CAD SaaS Onshape, starting from the FIA 2026 F1 Technical Regulations - Section C - Issue 15. The regulations firstly define the reference volumes wherein the rear wing must be completely contained in corner mode. It was decided to model the profiles (RV-RV-PROFILES) the endplate (RV-RWEP-BODY) and pylons (RV-RW-PYLON). A noticeable absence, later discussed, is that of the SLM Fairing and Bracket (RW-SLM-FAIRING and RW-BRACKET), which could have lead to further aerodynamic considerations, but was not modelled.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/RV.png" class="img-fluid figure-img"></p>
<figcaption>The reference volumes defined in the ruleset</figcaption>
</figure>
</div>
<p>Later the regulations also define sectional characteristics for the various elements describing the rear wing, prescribing visibility, curvature limits, allowed angles and thicknesses for each component.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/RV+RW.png" class="img-fluid figure-img"></p>
<figcaption>An example of a rear wing model completely contained within the reference volumes</figcaption>
</figure>
</div>
<p>The initial geometry, consisting of an assembly of:</p>
<ul>
<li>endplate</li>
<li>pylon</li>
<li>profiles</li>
</ul>
<p>Is shown in the following figure:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The initial geometry</figcaption>
</figure>
</div>
<p>A few comments can be made regarding the initial design. Due to a lack of expertise with CAD modelling the endplates are extremely simple, generated through a series of solid extrusions, with filleted edges. This creates a very squared look, with a rounded rectangle section in the streamwise direction, completely aligned with the <span class="math inline">\(x\)</span> axis. The pylons are similarly extruded and filleted. Both structures thus show a thick trailing edge, one of many areas of possible improvement.</p>
<p>The profiles, on the other hand are generated as surfaces, and thus provide a more polished result. The third element trailing edge is clearly not straight, giving rise to a wavy pattern which is of dubious effectiveness. The three profiles have been developed from scratch (although starting from a set of known <code>.dat</code> files had been considered<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>) using 2D splines. The first element has a larger chord, while the following two provide an increase in angle of attack and have a shorter chord. The wing surface spanwise shape has been controlled through the usage of 3D splines.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yNormalProfiles_y00.05.png" class="img-fluid figure-img"></p>
<figcaption>The three profiles at the midline, i.e.&nbsp;y=0, shown in a 2D section of the mesh</figcaption>
</figure>
</div>
<p>In conclusion, the initial geometry was deliberately designed with many details that left ample margins of improvement and explorations. A real F1 design cycle would certainly begin from a much more effective starting point, coming from both expertise and intuition.</p>
</section>
<section id="a-note-on-automation" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="a-note-on-automation"><span class="header-section-number">2.3</span> 2.3 A Note on Automation</h3>
<p>Smart CFD utilization requires the user to intervene only in areas of pre-processing, running and post-processing where critical evaluations must be made. A very hands-on approach may naively force the user to lauch each command sequentially analyzing the output at each step of the process. While not wrong many energies and resources would be wasted in repetitive tasks, which may incidentally cause lack of attention to details, leading to poor results. As a consequence script automation is a requirement for any CFD user. The simulations presented in this report were all run through bash automation, launching an <code>Allrun</code> script that sequentially invoked OpenFOAM commands or python scripts that interacted with Paraview to extract quantities of interest and images. This method has a secondary advantage: any tweak to the configuration can be instantaneously applied across many commmands and even many simulations, leading to a much less error prone pipeline. An example of the <code>Allrun</code> script is shown in the <a href="#appendix-code-automation-example">Appendix</a>, to highlight the capabilities (and shortcomings) of the developed process.</p>
</section>
<section id="meshing" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="meshing"><span class="header-section-number">2.4</span> 2.4 Meshing</h3>
<p>After many failed attempts at meshing using the native OpenFOAM snappyHexMesh software, particularly with regards to the prism layer generation (often generating far less layers than the required amount in the <code>snappyHexMeshDict</code>) a different route was attempted: the cfMesh software provides similar cartesian mesh quality to snappyHexMesh, with less configuration options and a much faster turnaround time<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. This allowed a much quicker and more efficient development of a <code>meshDict</code> file that constructed a good quality mesh, with user specified refinement edges, surfaces, regions and more than sufficient prism layer extrusion.</p>
<p>Taking some suggestions from the excellent <a href="https://www.linkedin.com/pulse/simulating-williams-fw43bar-part-1-all-simulations-wrong-david-penner/">LinkedIn post by David Penner</a> a base cell size on the surface of the rear wing was established at about 5 mm. Having to juggle resources with a limited hardware refinement regions had to be carefully analyzed. The solution utilized in the following report consist of the following mesh refinement strategy:</p>
<ul>
<li>edge refinement at the profiles leading edge and trailing edge. This was obtained through two OpenFOAM commands used in conjuction. Firstly by running <code>surfaceFeatureEdges -angle 2</code> all the angles in the rear wing geometry are computed and angles below two degrees (a threshold selected through trial and error in order to select all leading and trailing edge features) generate a splitting of the geometry into separate <code>.fms</code> files. Later the command <code>FMSToSurface -exportFeatureEdges</code> exports the <em>pointy</em> edges into a <code>.vtk</code> file that can be then used by cfMesh through the <code>edgeMeshRefinement</code> dictionary</li>
<li>surface refinement on the rear wing <code>.stl</code> surface</li>
<li>a first refinement box, closer to the wing, with the aim of modelling the wake of the wing</li>
<li>a second refinement box, to allow a smooth transition from the coarse freestream mesh to the finer cells in the first refinement box</li>
<li>generation of prism layers, with controls on the first cell height, expansion ratio and number of extruded layers</li>
</ul>
<p>A few quick comments can be made by comparatively looking at mesh slices coming from snappyHexMesh and cfMesh:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yNormalGap_y00sHM.png" class="img-fluid figure-img"></p>
<figcaption>A centerline slice of the mesh created with snappyHexMesh</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yNormalGap_y00cfM.png" class="img-fluid figure-img"></p>
<figcaption>A centerline slice of the mesh created with cfMesh</figcaption>
</figure>
</div>
</div>
<p>While snappyHexMesh builds very consistent layers cfMesh adapts the thickness to the surrounding cells (to maintain good mesh quality), a strategy that becomes problematic in refinement regions, as the prism layer becomes much thinner (possibly getting out of the desired <span class="math inline">\(y^+\)</span> range). On the other hand the next two pictures tell a totally different side of the story:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yNormalGap_y04sHM.png" class="img-fluid figure-img"></p>
<figcaption>A slice close to the endplate of the mesh created with snappyHexMesh</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yNormalGap_y04cfM.png" class="img-fluid figure-img"></p>
<figcaption>A slice close to the endplate of the mesh created with cfMesh</figcaption>
</figure>
</div>
</div>
<p>In this second case the layer extrusion procedure on the pressure side and leading edge of the second element<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> failed and no prismatic layer was created.</p>
<p>Another interesting observation can be made regarding the refinement algorithm for the two software options: transitioning from a single cell to two refined cells (the so-called split-quad, a pentagon obtained by refinement) snappyHexMesh tries to maintain perfectly orthogonal angles. Conversely cfMesh deforms the cell edges so that each cell is a convex pentagon. While apparently unmotivatedly complicated, the strategy applied by cfMesh is actually helpful at limiting both skewness and non-orthogonality, as the face connecting the owner and neighbour cell is angled in such a way that the vector connecting the two cell centers is a lot more similar to the face perpendicular bisector (in 2D) a.k.a. the face centered normal vector (in 3D). An excellent reading regarding mesh introduced errors can be found in the <a href="https://cfmesh.com/is-it-always-the-mesh-part-1-discretisation-basics-and-mesh-quality-metrics/">Is it Always the Mesh?</a> series, found in the cfMesh blog.</p>
<p>Finally, a discussion regarding the boundary layer description: the <em>low-Re</em> approach is generally considered to be superior in the description of high gradients and separation regions, and it might thus seem logical to aim for a <span class="math inline">\(y^+\)</span> of approximately 1 (well within the viscous sublayer) on the rear wing surface. This is certainly the topic for an interesting comparison, with and without wall functions, but is undoubtedly out of reach for the hardware available, leading to the necessary usage of wall functions (the so called <em>high-Re</em> approach). This is done through the <code>nutUSpaldingWallFunction</code> present in OpenFOAM, which is capable of handling a more broad spectrum of <span class="math inline">\(y^+\)</span> values thanks to a continous blending function. A thorough analysis of this implementation choice might also be of interest, compared to standard wall functions that are intended to work only in the log-law region.</p>
<p>Even though the choice of wall function implementation should provide some help if the first cell center is too close to the surface, a target value of <span class="math inline">\(30&gt;y^+&gt;200\)</span> was selected, and the automated bash script provided data extraction to verify the condition on the wing surface, as shown in the following figures<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yPlusPlot_y_00.01.png" class="img-fluid figure-img"></p>
<figcaption>The y+ values along a slice of the rear wing profiles at a station 0.01 m from the centerline (since the centerline lies in the plane of symmetry data extraction proved to be lousy, as expected)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yPlusPlot_y_00.30.png" class="img-fluid figure-img"></p>
<figcaption>The y+ values along a slice of the rear wing profiles at a station 0.3 m from the centerline</figcaption>
</figure>
</div>
<p>By automatically extracting these <span class="math inline">\(y^+\)</span> images at 10 different spanwise stations on the profiles, and at 5 stations on the endplates, every simulation could be checked regarding the compliance with appropriate first cell heights.</p>
</section>
<section id="physics-numerics" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="physics-numerics"><span class="header-section-number">2.5</span> 2.5 Physics &amp; Numerics</h3>
<p>The simulations were performed using OpenFOAM’s simpleFoam solver, a steady-state incompressible solver, alongside RANS modelling for turbulence. The complete solver configuration is detailed below.</p>
<section id="solver-settings" class="level4" data-number="2.5.1">
<h4 data-number="2.5.1" class="anchored" data-anchor-id="solver-settings"><span class="header-section-number">2.5.1</span> 2.5.1 Solver Settings</h4>
<p>The following table summarizes the key numerical settings used in the simulation:</p>
<ul>
<li><strong>Application</strong>: <code>simpleFoam</code> (steady-state incompressible)</li>
<li><strong>Turbulence Model</strong>: k-<span class="math inline">\(\omega\)</span> SST (Shear Stress Transport)</li>
<li><strong>Time steps</strong>: 500 iterations (pseudo-time iterations, being steady-state)</li>
<li><strong>Freestream velocity</strong>: <span class="math inline">\(U_{\infty} = 50\)</span>,m/s</li>
</ul>
<p>The governing equations are solved using the SIMPLE algorithm(Semi-Implicit Method for Pressure Linked Equations), as the simpleFoam application name suggests, with 3 non-orthogonal correctors, due to the geometrical complexity of the wing and its prismatic layers. It was later noticed in the output of the checkMesh command that the maximum non-orthogonality was below <span class="math inline">\(65^\circ\)</span>, with an average of <span class="math inline">\(\approx5^\circ\)</span>. These low values serve to show the quality of the cfMesh algorithm, and suggest that the resulting mesh should likely provide good results with a single non-orthogonal corrector, possibly even none. The maximum skewness was found to be <span class="math inline">\(\approx2.6\)</span>, on less than 50 cells out of the 8 millions used in the base mesh, once more proving the good quality of the mesh constructed by cfMesh.</p>
<p>The linear solver settings used for the simulation, found in the <code>fvSolution</code> file, are reported in the table below:</p>
<p><strong>Table 1: Linear solver settings</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Solver</th>
<th style="text-align: left;">Smoother</th>
<th style="text-align: left;">Tolerance</th>
<th style="text-align: left;">Rel. Tol</th>
<th style="text-align: left;">Sweeps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(p\)</span></td>
<td style="text-align: left;">GAMG</td>
<td style="text-align: left;">GaussSeidel</td>
<td style="text-align: left;">1e-7</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(U\)</span></td>
<td style="text-align: left;">smoothSolver</td>
<td style="text-align: left;">GaussSeidel</td>
<td style="text-align: left;">1e-8</td>
<td style="text-align: left;">0.1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(k\)</span></td>
<td style="text-align: left;">smoothSolver</td>
<td style="text-align: left;">GaussSeidel</td>
<td style="text-align: left;">1e-8</td>
<td style="text-align: left;">0.1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\omega\)</span></td>
<td style="text-align: left;">smoothSolver</td>
<td style="text-align: left;">GaussSeidel</td>
<td style="text-align: left;">1e-8</td>
<td style="text-align: left;">0.1</td>
<td style="text-align: left;">1</td>
</tr>
</tbody>
</table>
</div>
<p>The discretization schemes used to move from the Navier-Stokes to equations to a set of algebraic equations, found in the <code>fvSchemes</code> file, is described in the following table:</p>
<p><strong>Table 2: Discretization schemes</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Operator</th>
<th style="text-align: left;">Scheme</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Time derivative</td>
<td style="text-align: left;">Steady-state</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gradient</td>
<td style="text-align: left;">Gauss linear (cell-limited for <span class="math inline">\(U\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Divergence</td>
<td style="text-align: left;">linearUpwindV for momentum, upwind for turbulence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Laplacian</td>
<td style="text-align: left;">Gauss linear (corrected)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Interpolation</td>
<td style="text-align: left;">Linear</td>
</tr>
<tr class="even">
<td style="text-align: left;">Normal gradient</td>
<td style="text-align: left;">Corrected</td>
</tr>
</tbody>
</table>
</div>
<p>As it can be noticed, the schemes used aim for second order convergence (<code>linear</code>), a standard requirement in modern industrial CFD, only dropping to first order (<code>upwind</code>), for the discretization of the divergence terms in the turbulence two equation model; cell-limited and bounded second order schemes are used to avoid unphysical oscillations.</p>
</section>
<section id="boundary-conditions" class="level4" data-number="2.5.2">
<h4 data-number="2.5.2" class="anchored" data-anchor-id="boundary-conditions"><span class="header-section-number">2.5.2</span> 2.5.2 Boundary Conditions</h4>
<p>The computational domain consisting of 7 boundary patches applies the following BC:</p>
<ul>
<li><strong>inlet</strong>: Velocity inlet with fixed velocity, <span class="math inline">\(\vec{U} = (50, 0, 0)\)</span>,m/s</li>
<li><strong>outlet</strong>: Pressure outlet with fixed gauge pressure, <span class="math inline">\(p = 0\)</span>,Pa</li>
<li><strong>rearWing</strong>: No-slip condition, <span class="math inline">\(\vec{U}_{wall} = 0\)</span></li>
<li><strong>lowerWall</strong>: Fixed velocity moving ground, <span class="math inline">\(\vec{U} = (50, 0, 0)\)</span>,m/s</li>
<li><strong>symmetry</strong>: Symmetry plane at <span class="math inline">\(y = 0\)</span></li>
<li><strong>outside</strong>: Far-field slip boundary</li>
<li><strong>upperWall</strong>: Far-field slip boundary</li>
</ul>
<p>Boundary conditions applied in the turbulence model equations are detailed in the following list, only highlighting the choices that were actively considered with respect to a default tutorial.</p>
<ul>
<li><strong>Inlet</strong>: Fixed values: <span class="math inline">\(k = 0.01\)</span>,m<span class="math inline">\(^2\)</span>/s<span class="math inline">\(^2\)</span>, <span class="math inline">\(\omega = 700\)</span>,rad/s; coming from Spalart &amp; Rumsey <span class="citation" data-cites="spalart2007">[@spalart2007]</span>, as suggested by <a href="https://www.linkedin.com/pulse/simulating-williams-fw43bar-part-1-all-simulations-wrong-david-penner/">Penner</a>, and calculated <span class="math inline">\(\nu_t\)</span></li>
<li><strong>Walls (rearWing, lowerWall)</strong>: Wall functions using <code>nutUSpaldingWallFunction</code> for <span class="math inline">\(\nu_t\)</span>, <code>kqRWallFunction</code> for <span class="math inline">\(k\)</span> and <code>omegaWallFunction</code> for <span class="math inline">\(\omega\)</span></li>
<li><strong>Outlet</strong>: Inlet-outlet conditions for <span class="math inline">\(k\)</span> and <span class="math inline">\(\omega\)</span>, with calculated <span class="math inline">\(\nu_t\)</span></li>
</ul>
<p>In order to get a better convergence of steady steady iterations the initial conditions were given by:</p>
<ul>
<li>Velocity: uniform <span class="math inline">\(U = (50, 0, 0)\)</span>,m/s</li>
<li>Gauge pressure: uniform <span class="math inline">\(p = 0\)</span>,Pa</li>
</ul>
<p>The linear model solver potentialFoam was used from this starting condition to obtain a velocity field that could comply with the compatibility conditions (i.e.&nbsp;guaranteeing coherence between BC and IC). Once potentialFoam convergence was reached the resulting field was used as an initial condition for the RANS model solved with simpleFoam, adding the initial conditions:</p>
<ul>
<li>Turbulent kinetic energy: <span class="math inline">\(k = 0.01\)</span>,m<span class="math inline">\(^2\)</span>/s<span class="math inline">\(^2\)</span></li>
<li>Specific dissipation rate: <span class="math inline">\(\omega = 700\)</span>,rad/s</li>
</ul>
<p>The flow was initialized with uniform freestream conditions and solved for a number of iterations sufficient to reach convergence. To estimate convergence first, as suggested by the brilliant page <a href="https://cfd.university/blog//how-to-determine-the-best-stopping-criterion-for-cfd-simulations">cfd.university</a> the evolution of equation residuals was used to evaluate whether the first simulation was approaching convergence, divergence or an oscillatory plateau. Inspection of the following image shows a tendency towards convergence with small size oscillations that will predictably continue as long as the simulation is carried out.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/residualsGraph.png" class="img-fluid figure-img"></p>
<figcaption>The residuals evolution for the first simulation</figcaption>
</figure>
</div>
<p>Given the satisfactory converged appearance of the residuals, the next step suggested is to look at many different integral quantities, to evaluate the approach to a converged state of different flow quantities (as mentioned in the webpage lift coefficient is mainly driven by pressure, while the drag coefficient is more influenced by velocity gradients, thus using both to understand convergence gives a better look at the evolution of different aspects of the flow solution). In this case it as decided that lift, drag and moment coefficients should be analyzed, and thus a python script extracting the time evolution of these three integral quantities was developed and added to the bash script automation, so that convergence of each simulation could be quickly evaluated at a glance. The results for the basis simulation are shown in the next set of images:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/CD_evolution.png" class="img-fluid figure-img"></p>
<figcaption>The CL evolution for the first simulation</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/CL_evolution.png" class="img-fluid figure-img"></p>
<figcaption>The CD evolution for the first simulation</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/CM_evolution.png" class="img-fluid figure-img"></p>
<figcaption>The CM evolution for the first simulation</figcaption>
</figure>
</div>
<p>As expected convergence of the three coefficients does not seem to happen exactly at the same pseudo-time iteration, nonetheless at the end of the 500 iterations a clear steady state converged value is approached by all three. Once these steps are completed the same <a href="https://cfd.university/blog//how-to-determine-the-best-stopping-criterion-for-cfd-simulations">webpage</a> suggests that an Asymptotic Convergence Threshold (ACT) should be established through a script that dynamically evaluates the state of the simulation. This would certainly help at minimizing the number of iterations utilized (thus wasting minimal computing resources), however the criterion of 500 iterations was considered sufficient for this simple case<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>, and the implementation of the ACT framework was left as a work for a later project.</p>
<p>Finally, as a result of this first study on convergence a window size of 200 iterations was chosen to compute average values the converged steady state integral coefficients to be evaluated when comparing different rear wing geometries.</p>
</section>
</section>
<section id="grid-convergence-study" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="grid-convergence-study"><span class="header-section-number">2.6</span> 2.6 Grid Convergence Study</h3>
<p>Once a solid simulation framework was established a mesh convergence study was performed using cfMesh to guarantee grid-independent solutions. Three mesh densities were evaluated on the initial geometry: a coarse one, a medium one and a fine one. The following table summarizes the mesh configurations and key settings:</p>
<p><strong>Table 3: Mesh configuration summary for convergence study</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Coarse</th>
<th style="text-align: left;">Medium</th>
<th style="text-align: left;">Fine</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Number of cells</td>
<td style="text-align: left;">1,490,057</td>
<td style="text-align: left;">4,953,036</td>
<td style="text-align: left;">7,709,701</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cell size (1st refinement box)</td>
<td style="text-align: left;">0.08</td>
<td style="text-align: left;">0.0156</td>
<td style="text-align: left;">0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cell size (2nd refinement box)</td>
<td style="text-align: left;">0.15</td>
<td style="text-align: left;">0.0625</td>
<td style="text-align: left;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cell size (wing surface)</td>
<td style="text-align: left;">0.035</td>
<td style="text-align: left;">0.005</td>
<td style="text-align: left;">0.0035</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cell size (sharp edge refinement)</td>
<td style="text-align: left;">0.0017</td>
<td style="text-align: left;">0.0015</td>
<td style="text-align: left;">0.0013</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prismatic layers number</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1st prismatic layer max. thickness</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.008</td>
</tr>
</tbody>
</table>
</div>
<p>As can be seen the first cell maximum height was kept fixed, and the value was computed by estimating a <span class="math inline">\(y^+\approx100\)</span> using a flat plate analogy. All other parameters are instead refined moving from a mesh to finer one.</p>
<p>The next table presents the aerodynamic coefficients extracted through windowing and averaging for each mesh level:</p>
<p><strong>Table 4: Aerodynamic coefficients for mesh convergence study</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Mesh Level</th>
<th style="text-align: left;"><strong><span class="math inline">\(C_{D,mean}\)</span></strong></th>
<th style="text-align: left;"><strong><span class="math inline">\(C_{L,mean}\)</span></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Coarse</td>
<td style="text-align: left;">0.4585</td>
<td style="text-align: left;">-2.4051</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medium</td>
<td style="text-align: left;">0.4450</td>
<td style="text-align: left;">-2.4286</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fine</td>
<td style="text-align: left;">0.4305</td>
<td style="text-align: left;">-2.3700</td>
</tr>
</tbody>
</table>
</div>
<p>The grid convergence analysis was performed using the Grid Convergence Index, in the derivation presented by Celik <em>et al.</em> <span class="citation" data-cites="celik2008">[@celik2008]</span>, which will be now briefly summarized.</p>
<p>First a mesh representative grid spacing is computed for the three grids as: <span class="math display">\[h_j = \left(\frac{1}{N_{cells}}\sum_{i=1}^{N_{cells}}\Delta V_i\right)^{1/3}\]</span></p>
<p>For <span class="math inline">\(j\in[1,2,3]\)</span>, representing the three refinement levels ordered as 1=fine, 2=medium and 3=coarse.</p>
<p>Then the refinement ratio between successive grids is defined as: <span class="math display">\[r_{ij} = \frac{h_i}{h_j}\]</span></p>
<p>And for meaningful convergence results one should aim for <span class="math inline">\(r_{ij}\geq1.3\)</span>, in order to evaluate meshes that vary in a significant enough manner.</p>
<p>By calling <span class="math inline">\(\phi_i\)</span> the evaluated quantity for the <span class="math inline">\(i\)</span>-th grid (in this case the two integral coefficients <span class="math inline">\(C_D\)</span> and <span class="math inline">\(C_L\)</span>) a useful indicator can at this point be defined as the <em>convergence ratio</em>: <span class="math display">\[CR = \frac{\phi_2 - \phi_1}{\phi_3 - \phi_2}\]</span></p>
<p>Notice that:</p>
<ul>
<li><span class="math inline">\(CR&lt;1\)</span> indicates oscillatory divergence</li>
<li><span class="math inline">\(-1\leq CR\leq0\)</span> indicates oscillatory convergence</li>
<li><span class="math inline">\(0\leq CR\leq1\)</span> indicates monotonic convergence</li>
<li><span class="math inline">\(CR\geq1\)</span> indicates monotonic divergence</li>
</ul>
<p>At this point a loop procedure is entered:</p>
<ol type="1">
<li>a value for the order of convergence <span class="math inline">\(p\)</span> is guessed, usually 1 or 2</li>
<li>define <span class="math inline">\(s = \text{sign}(\frac{\phi_3 - \phi_2}{\phi_2 - \phi_1})\)</span></li>
<li>update <span class="math inline">\(p = \frac{1}{\log{r_{21}}}|\log(|\frac{\phi_3 - \phi_2}{\phi_2 - \phi_1}|)+\log(\frac{r_{21}^p - s}{r_{32}^p-s})|\)</span></li>
<li>exit the loop when <span class="math inline">\(p\)</span> converges</li>
</ol>
<p>With the order of convergence we can compute the Richardson extrapolated value as: <span class="math display">\[\phi_{expected} = \phi_1 + \frac{\phi_1 - \phi_2}{r_{21}^p - 1}\]</span></p>
<p>Also, we define: <span class="math display">\[\varepsilon_{ij}=\left|\frac{\phi_j - \phi_i}{\phi_j}\right|\]</span></p>
<p>So that we can compute the GCI as: <span class="math display">\[GCI_{ij} = \frac{1.25\cdot\varepsilon_{ij}}{r_{ij}^p-1}\]</span></p>
<p>Which can be expressed as a percentage when multiplied by 100. The target value should be to have <span class="math inline">\(GCI\leq5\%\)</span> when doing parametric studies, and <span class="math inline">\(GCI\leq1\%\)</span> when extracted values are of paramount importance.</p>
<p>We finally define the <em>asymptotic range</em> as: <span class="math display">\[AR = \frac{GCI_{32}}{r_{21}^p-1}\]</span></p>
<p>Which offers a good measure of much further should the mesh be refined, and gets closer and closer to 1 as the grid becomes refined <em>enough</em>.</p>
<p>Using the GCI toolbox, the refinement ratios found are:</p>
<ul>
<li><span class="math inline">\(r_{21} = 1.16\)</span></li>
<li><span class="math inline">\(r_{32} = 1.49\)</span></li>
</ul>
<p>Which emphasizes that the variation between the medium and the fine cell is not large enough. This nonetheless contrasted with the hardware limitations, and was accepted for the subsequent analysis.</p>
<p>The convergence ratio computed for the drag coefficient in this case is <span class="math inline">\(CR=1.07\)</span>, indicating monotonic divergence, while the same indicator for the lift coefficient comes out to be <span class="math inline">\(CR=-2.49\)</span>, indicating oscillatory divergence.</p>
<p>This is, at a very practical level, a terrible result: the finest mesh is not fine enough to establish a mathematically converging behaviour with respect to the medium and coarse one, and thus for both drag and lift the order of convergence numerically computed is a <span class="math inline">\(p=\text{NaN}\)</span> value, not allowing a GCI estimate.</p>
<p>Having met the hardware limit for the finest mesh possible it was not possible to go further with the refinement, and thus it was decided to accept a risk: the fine mesh would be used at this stage for the aerodynamic development of the wing, and the described limitation will be addressed and fully resolved in a later section by offloading the final geometry to an AWS cloud computing instance for a proper grid convergence verification, to establish a proper GCI<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>.</p>
<p>This limitation will be addressed and fully resolved in a later section by offloading the final geometry to an AWS cloud computing instance for a proper grid convergence verification.</p>
</section>
<section id="post-processing" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="post-processing"><span class="header-section-number">2.7</span> 2.7 Post-Processing</h3>
<p>As previously mentioned the post-processing workflow is fully automated through the <code>Allrun</code> script, which orchestrates all visualization and data extraction tasks using ParaView and custom Python scripts. The complete workflow consists of the following stages:</p>
<section id="force-coefficients-computation" class="level4" data-number="2.7.1">
<h4 data-number="2.7.1" class="anchored" data-anchor-id="force-coefficients-computation"><span class="header-section-number">2.7.1</span> 2.7.1 Force Coefficients Computation</h4>
<p>Force coefficients were computed using the OpenFOAM <code>forceCoeffs</code> function object configured inside <code>system/forceCoeffs</code>:</p>
<ul>
<li><strong>Reference area</strong>: <span class="math inline">\(A_{ref} = 0.2\)</span>,m<span class="math inline">\(^2\)</span></li>
<li><strong>Direction vectors</strong>: Lift = <span class="math inline">\((0,0,1)\)</span>, Drag = <span class="math inline">\((1,0,0)\)</span>, Pitch axis = <span class="math inline">\((0,1,0)\)</span></li>
<li><strong>Freestream velocity</strong>: <span class="math inline">\(U_{\infty} = 50\)</span>,m/s</li>
</ul>
<p>The function object outputs:</p>
<ul>
<li><span class="math inline">\(C_L\)</span>: Lift coefficient (negative for downforce)</li>
<li><span class="math inline">\(C_D\)</span>: Drag coefficient</li>
<li><span class="math inline">\(C_M\)</span>: Pitching moment coefficient</li>
</ul>
<p>Each coefficient is given as the sum of pressure and viscous contributions:</p>
<ul>
<li><span class="math inline">\(C_{L,p}\)</span>, <span class="math inline">\(C_{D,p}\)</span>, <span class="math inline">\(C_{M,p}\)</span>: Pressure forces</li>
<li><span class="math inline">\(C_{L,visc}\)</span>, <span class="math inline">\(C_{D,visc}\)</span>, <span class="math inline">\(C_{M,visc}\)</span>: Viscous forces</li>
</ul>
<p>Notice that aerobalance data, i.e.&nbsp;loads as they are divided between the front and rear wheels, are extremely useful and common in modern racing aerodynamics, as they offer a chance to investigate stability and drivability. Nonetheless having a simulation only looking at the rear wing this balance data does not really make any sense, and will thus not be detailed in this report.</p>
<p>The results are written at each time step to <code>postProcessing/forceCoeffs/</code>, enabling convergence monitoring directly from the terminal during runtime<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<p>While force coefficients are computed at runtime, both to verify convergence and to allow windowing and averaging for more accurate results, other flow quantities of interest are extracted later by running <code>simpleFoam -postProcess</code>, which looks for a <code>system/postProcessDict</code> file. This is done in order to reduce the computational overhead at runtime, as post-processing tools were found to increase the memory requirement, sometimes leading to OOM fatal errors. The <code>postProcessDict</code> is used to extract:</p>
<ul>
<li>wall shear stress field on the wing surface, <span class="math inline">\(\tau_w\)</span></li>
<li>wall bounded streamlines, to mimic flow-vis paint visualizations</li>
<li>turbulence normalized wall distance, <span class="math inline">\(y^+\)</span></li>
<li>the <span class="math inline">\(\lambda_2\)</span> vortex criterion</li>
</ul>
<p>ParaView was then used through the <code>results3DPostProcessing.py</code> script to generate 3D visualizations including pressure coefficient fields, wall shear stress magnitude<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>, <span class="math inline">\(\lambda_2\)</span> criterion, and velocity field representations. Wall-bounded streamlines were extracted to visualize flow attachment and separation patterns. This same script is used to compute field variables as <span class="math inline">\(C_p\)</span> and <span class="math inline">\(C_p^{tot}\)</span><a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>, and it also extracts <span class="math inline">\(C_p\)</span> and <span class="math inline">\(y^+\)</span> data along spanwise slices. Examples of the extracted images are shown in the following pictures:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/cpPlot_y_00.01.png" class="img-fluid figure-img"></p>
<figcaption>A visualization of the extracted Cp data, shown for a spanwise station</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/cpPlot_y_00.30.png" class="img-fluid figure-img"></p>
<figcaption>A visualization of the extracted Cp data, shown for a second spanwise station</figcaption>
</figure>
</div>
</div>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/WSS_Streamlines_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A visualization of the wall shear stress, showing superimposed limiting streamlines on half of the geometric model</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/WSS_Streamlines_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>A visualization of the wall shear stress, showing superimposed limiting streamlines on half of the geometric model</figcaption>
</figure>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/Lambda2_CpTot_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>A visualization of the most important vortical structures through the Lambda2 criterion, coloured by the total pressure coefficient</figcaption>
</figure>
</div>
<p>While 3D images are useful for getting a broad picture of the overall flow development, and a good conceptual understanding of the most important flow features, they do not allow precise tracking of structures, and are thus less suited to geometry design and optimization. With this in mind a <code>results3DPostProcessing.py</code> script was developed, which generates high resolution images of a series of slices taken by moving cutting planes in the <span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span> and <span class="math inline">\(z\)</span> directions. Such pictures were generated to show <span class="math inline">\(C_p\)</span> and <span class="math inline">\(C_p^{tot}\)</span> distributions on the wing surface and in the wake, including the same representation with Line Integral Convolution (LIC) superimposed<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>. A few examples of the resulting 2D visualizations are shown in the following:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/xNormalCpTotLIC_77_xp00.57.png" class="img-fluid figure-img"></p>
<figcaption>A Cp_tot+LIC visualization of an x-normal slice of the rear wing</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/yNormalCp_10_yp00.10.png" class="img-fluid figure-img"></p>
<figcaption>A Cp visualization of a y-normal slice of the rear wing</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/zNormalCpTot_58_zp00.73.png" class="img-fluid figure-img"></p>
<figcaption>A Cp_tot visualization of a z-normal slice of the rear wing</figcaption>
</figure>
</div>
<p>All 2D renderings are also combined into mp4 video animations, showing the evolution of structures in the three directions:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/Z_8Aim5R0g8" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Finally a custom Python script (<code>caseSummary.py</code>) performs automated data extraction from the pseudo-time history of the simulation and computes mean values over the last 250 iterations to ensure stable averages. This script also updates the master <code>casesSummary.csv</code> file, available for overall numerical results comparison, with all extracted data.</p>
<p>A final PDF report highlighting some details regarding convergence history, simulation setup and results is automatically generated using Marp from a Markdown template.</p>
<hr>
</section>
</section>
</section>
<section id="results-and-discussion" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="results-and-discussion"><span class="header-section-number">3</span> 3. Results and Discussion</h2>
<p>The development of an evolution to the starting geometry required going through 14 different iteration. Not all of these will be discussed in detail, as many subsequent geometry changes were aimed at solving similar aerodynamic issues.</p>
<p>First of all the starting geometry results, coming from the fine (7.7 million cells) mesh, are to be discussed, in order to introduce the main area of improvement<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>.</p>
<section id="initial-results" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="initial-results"><span class="header-section-number">3.1</span> 3.1 Initial results</h3>
<p>The initial geometry with non optimized 2D profiles, bluff endplates and bluff pylons returned a drag coefficient of <span class="math inline">\(C_D=0.431\)</span> and a lift coefficient of <span class="math inline">\(C_L=-2.370\)</span>, both averaged over the final 250 iterations.</p>
<p>Looking at the wall shear stress distribution superimposed with limiting streamlines it is possible to highlight a few key observations:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_03/WSS_Streamlines_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A wall shear stress visualization with limiting streamlines from the bottom right view</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_03/WSS_Streamlines_BotRear.png" class="img-fluid figure-img"></p>
<figcaption>A wall shear stress visualization with limiting streamlines from the bottom view</figcaption>
</figure>
</div>
<p>The flow appears to remain attached for the entirety of the first profile. The second and third element exhibit some weak flow in the trailing edge area, with the limiting streamlines of the third element showing detached flow and recirculation. The flow near at the profiles-endplate junction is attached and <em>healthy</em>, but a very large region of separation is visible in the lower portion, where at least a saddle point and a node point are clearly identifiable according to the topological interpretation of separated flows by Tobak and Peake <span class="citation" data-cites="tobak1982">[@tobak1982]</span>. The bottom views highlights the presence of some flow structure downstream of the blunt pylons, which can be better seen through the <span class="math inline">\(\lambda_2\)</span> criterion visualization:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_03/Lambda2_CpTot_BotRear.png" class="img-fluid figure-img"></p>
<figcaption>A Lambda2 visualization from the bottom view</figcaption>
</figure>
</div>
<p>A couple of V-shaped vortical separated structures extend downstream from each pylon, thus reducing efficiency with no apparent benefit. The <span class="math inline">\(\lambda_2\)</span> criterion also makes it possible to see three strong vortices forming at each endplate:</p>
<ul>
<li>at the top, the strongest one is caused by the pressure side flow spilling over, similarly to the classic tip vortex of any wing (albeit with a much more efficient result)</li>
<li>at the bottom the opposite effect is visible, where the low pressure between the endplates and the profiles draws in air from the outside</li>
<li>a vortex is released close to the bottom, where the endplate aggresively changes both the <em>dihedral</em> angle and the chord</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_03/Lambda2_CpTot_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A Lambda2 visualization from the bottom right view</figcaption>
</figure>
</div>
<p>The bottom view of the wall shear stress surface contour plot also shows an interesting aspect: while the leading edge of the second and third element are coloured red, showing high energy flow, the leading edge of the first element hints at weak flow development, with possible separation. The first element was initially designed with the leading edge aligned with the <span class="math inline">\(x\)</span>-axis, and this is the possible cause of this low energy region. To further investigate this flow behaviour <span class="math inline">\(y\)</span>-normal 2D slices were analyzed:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/e_ih8pUGe0o" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_03/yNormalCpTotLIC_12_yp00.12.png" class="img-fluid figure-img"></p>
<figcaption>A y-normal 2D slice Cp_tot visualization, at the y=0.12 m station</figcaption>
</figure>
</div>
<p>From the image the situation appears very clear: the low pressure of the suction side (and similarly the high pressure of the pressure side) bend the flow downward, causing an effective negative of attack of the first element leading edge. This in turn causes leading edge separation, which leads to a thick dissipative wake and a consequent increase in drag.</p>
</section>
<section id="design-evolution" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="design-evolution"><span class="header-section-number">3.2</span> 3.2 Design Evolution</h3>
<p>The rear wing design was thus evolved with a few corrections needed in mind:</p>
<ul>
<li>The pylon should use a streamlined cross section, specifically a symmetric profile</li>
<li>The wavy trailing edge, especially on the third element, increases the vorticity released in the wake, and thus drag</li>
<li>the first element leading edge should be aligned with the local partially downwards flow</li>
</ul>
<p>At the same time a few corrections were added as they were expected to introduce performance gains:</p>
<ul>
<li>The first element should have a longer chord, to maximize the angle of attack, and thus the suction, of the second and third element while remaining inside the regulatory bounding box <a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></li>
<li>The third element was made slimmer and more cambered</li>
<li>A Gurney flap was added for maximum downforce extraction by adding extreme camber at the trailing edge</li>
</ul>
<p>The evolved geometry can be seen in the next image:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_05/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The first evolution of the rear wing design</figcaption>
</figure>
</div>
<p>This design iteration provided a drag coefficient of <span class="math inline">\(C_D=0.510\)</span>, an 18.3% increase , and a lift coefficient of <span class="math inline">\(C_L=-2.722\)</span>, a 14.9% increase. Clearly the research of performance, i.e.&nbsp;downforce, was going in the right direction, but efficiency could be increased.</p>
<p>The revised pylon immediately proved effective, as the V-shaped vortical structure was heavily reduced and almost removed:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_05/Lambda2_CpTot_BotRear.png" class="img-fluid figure-img"></p>
<figcaption>A Lambda2 visualization from the bottom right view</figcaption>
</figure>
</div>
<p>The increase in downforce brings of course an unavoidable increase in the intensity of the endplate vortices, so part of the drag added is found there. Nonetheless the newfound suction also causes a more extreme endplate leading edge separation due to lateral cross flow, as can be seen in the next pair of images:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/bnaXpwF-t-E" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_05/zNormalCpTotLIC_35_zp00.50.png" class="img-fluid figure-img"></p>
<figcaption>A z-normal 2D slice Cp_tot visualization, at the z=0.49 m station</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_05/WSS_Streamlines_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A wall shear stress visualization with limiting streamlines from the bottom right view</figcaption>
</figure>
</div>
<p>The leading edge variation proved to be effective, as the first element separation was almost completely suppressed:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/8S0RSSDGykI" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_05/yNormalCpTotLIC_12_yp00.12.png" class="img-fluid figure-img"></p>
<figcaption>A y-normal 2D slice Cp_tot visualization, at the y=0.12 m station</figcaption>
</figure>
</div>
<p>Nonetheless by looking at the pressure distribution on the three sections it was possible to notice a pronounced pressure peak, with <span class="math inline">\(min(C_p)&lt;5\)</span>, which causes a strong adverse pressure gradient, which in turn increases the boundary layer thickness:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_05/cpPlot_y_00.20.png" class="img-fluid figure-img"></p>
<figcaption>A Cp-x plot, at the y=0.2 m station</figcaption>
</figure>
</div>
<p>For this reason the first element leading edge could be further optimized by making it more downwashing. This correction was added to the next important design iteration, which introduced a newly designed endplated, generated though a lofted surface, with the goal of making it smooth and reduce separation. All trailing edges were now thin and streamlined, thus pressure drag was expected to be much lower. The geometry is shown in the next figure:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_08/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The next evolution of the rear wing design</figcaption>
</figure>
</div>
<p>This design seemed to correctly address the issues of the previous geometry: the drag was reduced by 3.3%, to <span class="math inline">\(C_D=0.493\)</span>, while the lift coefficient increased by 2% to <span class="math inline">\(C_L=-2.777\)</span>. Some post-processing allowed to focus on the most promising development paths and problematic areas.</p>
<p>Firstly, as can be observed in the next image the smoothed endplate removed the vortex generated at the change in chord and dihedral previously highlighted, a good example of drag reduction:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_08/Lambda2_CpTot_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A Lambda2 visualization from the bottom right view</figcaption>
</figure>
</div>
<p>Some endplate leading edge separation remained present even after this evolution, although much weaker than that in the previous design, an issue to be addressed again with better alignment of the cross sections of the lofted geometry:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_08/WSS_Streamlines_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A wall shear stress visualization with limiting streamlines from the bottom right view</figcaption>
</figure>
</div>
<p>The following development focused on downforce generation, with the target of maximizing suction. Looking back at the regulation box for the profiles, i.e.&nbsp;the RV-RW-PROFILES reference volume, it was noticed that the vertical became smaller and smaller in the spanwise direction moving towards the tip. This forces the profiles to have a dihedral angle, but it also means that the angle of attack of the second and third element tend to reduce moving outwards. To counter this effect the chord of the tips of the second and third flaps was made smaller, while making it longer for the first element so that a larger angle of attack could fit within the reference volume. A second upgrade was the introduction of a rounded top side leading edge for the endplate, in order to reduce drag. Finally, a pretty aggressive cutout downstream of the third element was added in order to investigate its effectiveness, compared to the pre-2022 rear wing regulation. Ideally such a cutout should help mitigate the tip vortex intensity, thus increasing efficiency. This new geometry can be seen in the images below:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_10/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The next evolution of the rear wing design</figcaption>
</figure>
</div>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_08/Geometry_Top.png" class="img-fluid figure-img"></p>
<figcaption>A comparison of the geometric evolution. Old profiles design on the left</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_10/Geometry_Top.png" class="img-fluid figure-img"></p>
<figcaption>New profiles design on the right. Notice the chord reduction for the second and third element at the tip</figcaption>
</figure>
</div>
</div>
<p>The following image details the change in the last two profiles. By visual inspection it is also clear that the slot gap between the first and second element is not optimized, and the second element leading edge design probably leaves some room for better flow alignment.</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_08/yNormalFlapTE_y00.50.png" class="img-fluid figure-img"></p>
<figcaption>A comparison of the geometric evolution, from a slice of the mesh near the wingtip (old design)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_10/yNormalFlapTE_y00.50.png" class="img-fluid figure-img"></p>
<figcaption>New design. Notice the reduced chord and increased angle of attack on the second and third element</figcaption>
</figure>
</div>
</div>
<p>This renovated rear wing produced a significant jump forward in downforce, with the lift coefficient magnitude increasing by 4.9% to <span class="math inline">\(C_L=-2.912\)</span>; at the same time drag saw an uptick by 3.9%, getting to <span class="math inline">\(C_D=0.512\)</span>.</p>
<p>A nice finding was that endplate separation was almost completely eliminated by changing the cross section, as can be seen in the <span class="math inline">\(z\)</span>-normal video, or in the following images:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/PiH5JZXc4SQ" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_10/zNormalCpTotLIC_37_zp00.52.png" class="img-fluid figure-img"></p>
<figcaption>A z-normal 2D slice Cp_tot visualization, at the z=0.49 m station</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_10/WSS_Streamlines_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A wall shear stress visualization with limiting streamlines from the bottom right view</figcaption>
</figure>
</div>
<p>The above image shows that some trailing edge separation is present on the second and third profile. While acceptable on the third element, flow detaching from the second one is better avoided, a goal for next design iterations.</p>
<p>The suboptimal first slot gap design can be quantified by inspecting the following <span class="math inline">\(C_p-x\)</span> plot, where it is evident that the first element is generating lift at the trailing edge. Notice nonetheless a reduction in the suction peak at all leading edges:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_10/cpPlot_y_00.30.png" class="img-fluid figure-img"></p>
<figcaption>A Cp-x plot, at the y=0.3 m station</figcaption>
</figure>
</div>
<p>Finally inspection of the <span class="math inline">\(x\)</span>-normal animation showed some junction separation, suggesting that the wing tips designed could still be improved.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/u8wByIJwy7U" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_10/xNormalCpTotLIC_85_xp00.65.png" class="img-fluid figure-img"></p>
<figcaption>An x-normal 2D slice Cp_tot visualization, at the x = 0.68 m station</figcaption>
</figure>
</div>
<p>The next geometry focused on maintaining a high downforce, with some efficiency gain: it focused on slot gap effectiveness to reduce separation, and better leading edge alignement. The leading edge and trailing edge spanwise evolution was evolved using a more accurate lofting strategy<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a>. The endplate cutout was also reduced, as can be seen below:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_16/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The next evolution of the rear wing design</figcaption>
</figure>
</div>
<p>The effects of this evolution were immediatley apparent: downforce slightly changed to <span class="math inline">\(C_L=-2.914\)</span> (a negligible increase of 0.01%), while drag was reduced to <span class="math inline">\(C_D=0.491\)</span>, down 4.1%, a significant amount.</p>
<p>Separation on the second and third element was greatly reduced in intensity, and the endplate maintained attached flow throughout:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_16/WSS_Streamlines_BotRear.png" class="img-fluid figure-img"></p>
<figcaption>A wall shear stress visualization with limiting streamlines from the bottom view</figcaption>
</figure>
</div>
<p>Slot gap effectiveness was increased as expected, with the pressure profile showing a much healthier state:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_16/cpPlot_y_00.30.png" class="img-fluid figure-img"></p>
<figcaption>A Cp-x plot, at the y=0.3 m station</figcaption>
</figure>
</div>
<p>Looking at the <span class="math inline">\(x\)</span>-normal slices the large amount of junction losses and third element separation is evidently removed, causing a slimmer wake, evidence of effective drag reduction:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/eR6ss9yU4tE" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_16/xNormalCpTotLIC_85_xp00.65.png" class="img-fluid figure-img"></p>
<figcaption>An x-normal 2D slice Cp_tot visualization, at the x = 0.68 m station</figcaption>
</figure>
</div>
<p>The wing seemed to have no hugely problematic area, so it was decided that one final iteration would be developed before moving on. The aim of this final design was maximum downforce generation, thus an increase in the angle of attack of the second and third element was introduced, both at the root and at the tip.</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/yNormalProfiles_y00.05.png" class="img-fluid figure-img"></p>
<figcaption>The final version of the wing profiles (root section)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/yNormalProfiles_y00.50.png" class="img-fluid figure-img"></p>
<figcaption>The final version of the wing profiles (tip section)</figcaption>
</figure>
</div>
</div>
<p>The coefficients responded as expected, downforce spiking to the maximum value found in the entire design space of <span class="math inline">\(C_L=-2.950\)</span>, a 1.2% increase. Drag, as expected, saw an increment of 1.6%, getting to <span class="math inline">\(C_D=0.499\)</span>, which was considered adequate for the present research. While it is possible to go even more aggressive with the angle of of attack at the trailing edge managing separation would certainly get trickier, so more aggressive designs were left as a future topic.</p>
<p>It was interesting to notice that during the more recent developments, while reducing the separation at the endplate leading edge, the vortex midway through the endplate was back:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/Lambda2_CpTot_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A Lambda2 visualization from the bottom right view</figcaption>
</figure>
</div>
<p>This is actually a desirable effect<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> as it is caused by the expansion generated by the endplate. This expansion works together with the profiles to increase downforce, as visible in the next images:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/xNormalCp_70_xp00.50.png" class="img-fluid figure-img"></p>
<figcaption>Visualization of the pressure coefficient Cp (x-normal slice at x=0.5 m)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/zNormalCp_40_zp00.55.png" class="img-fluid figure-img"></p>
<figcaption>Visualization of the pressure coefficient Cp (z-normal slice at z=0.55 m)</figcaption>
</figure>
</div>
</div>
<p>A nice feature of this final design is the usage of slimmer profiles, which thus are able to produce considerable downforce with a lower drag generated<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a>. Junction separation was kept at a minimum, and the profiles seem to provide mostly attached flow down to the trailing edge:</p>
<p></p><div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/xXAd8A9fTbc" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div> <div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/mHuAHiiPkw0" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div><p></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/WSS_Streamlines_BotRight.png" class="img-fluid figure-img"></p>
<figcaption>A wall shear stress visualization with limiting streamlines from the bottom right view</figcaption>
</figure>
</div>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/xNormalCpTotLIC_85_xp00.65.png" class="img-fluid figure-img"></p>
<figcaption>Total pressure coefficient (x-normal slice at x=0.65 m)</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_17/yNormalCpTotLIC_22_yp00.22.png" class="img-fluid figure-img"></p>
<figcaption>Total pressure coefficient (y-normal slice at y=0.22 m)</figcaption>
</figure>
</div>
</div>
<p>The results of the design process are finally summarized in the following table, where <span class="math inline">\(\Delta\)</span> values are computed with respect to the initial geometry:</p>
<p><strong>Table 5: Aerodynamic coefficients for the analyzed rear wing configurations, with percentage deltas relative to the initial design</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Description</th>
<th style="text-align: left;"><span class="math inline">\(C_D\)</span></th>
<th style="text-align: left;"><span class="math inline">\(C_L\)</span></th>
<th style="text-align: left;"><span class="math inline">\(L/D\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Initial geometry</td>
<td style="text-align: left;">0.431</td>
<td style="text-align: left;">-2.370</td>
<td style="text-align: left;">-5.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Streamlined pylon, revised LE</td>
<td style="text-align: left;">0.510 (+18.3%)</td>
<td style="text-align: left;">-2.722 (+14.8%)</td>
<td style="text-align: left;">-5.33 (-3.1%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lofted endplate, thin TEs</td>
<td style="text-align: left;">0.493 (+14.4%)</td>
<td style="text-align: left;">-2.777 (+17.2%)</td>
<td style="text-align: left;">-5.63 (+2.4%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Revised profiles, endplate cutout</td>
<td style="text-align: left;">0.512 (+18.8%)</td>
<td style="text-align: left;">-2.912 (+22.9%)</td>
<td style="text-align: left;">-5.69 (+3.5%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Slot gap and LE refinement</td>
<td style="text-align: left;">0.491 (+13.9%)</td>
<td style="text-align: left;">-2.914 (+22.9%)</td>
<td style="text-align: left;">-5.93 (+7.8%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Increased AoA, final design</td>
<td style="text-align: left;">0.499 (+15.8%)</td>
<td style="text-align: left;">-2.950 (+24.5%)</td>
<td style="text-align: left;">-5.91 (+7.5%)</td>
</tr>
</tbody>
</table>
</div>
<p>The only comparison found online for the same 2026 regulation is the <a href="https://www.linkedin.com/pulse/simulating-f1-2026-rear-wing-article-2-power-aerodynamics-ted-l-w4skc/">LinkedIn article</a> by Ted L., where he reports a maximum downforce of 1414.5 N. Using the reference values to transform the lift coefficient into a force the optimal design turns out to produce about 1806.9 N, approximately 27.7% more downforce, indicating that at least some key design choices were taken in the correct direction.</p>
</section>
<section id="straight-line-mode-slm-configurations" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="straight-line-mode-slm-configurations"><span class="header-section-number">3.3</span> 3.3 Straight Line Mode (SLM) Configurations</h3>
<p>Once an appropriate high-downforce configuration was found four additional cases were simulated to evaluate the Straight Line Mode (SLM): a feature of the 2026 regulations that allows the rear wing to reduce flap incidence for lower drag during high-speed straights. These four designs were developed to evaluate different pivot point strategies, also looking at the choices made by F1 teams for the 2026 season.</p>
<section id="a-brief-comment-caveat" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="a-brief-comment-caveat"><span class="header-section-number">3.3.1</span> 3.3.1 A brief comment &amp; caveat</h4>
<p>The simulation of the wing presented in the previous sections did not involve the SLM fairing, which is the aerodynamic fairing that shields the mechanisms and actuators needed for straight line mode activation. This of course causes the results to be numerically off if compared to the actual numbers found on real 2026 F1 cars. Nonetheless the simulations were aimed at profiles and dihedral optimization, and thus the simulations were carried out without detailing the fairing. This discussion will become important in the following section, as the choice of fairing is heavily dependent on the SLM strategy chosen. As a result numbers regarding straight line mode should be read critically.</p>
</section>
<section id="alpine-style-slm" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="alpine-style-slm"><span class="header-section-number">3.3.2</span> 3.3.2 Alpine style SLM</h4>
<p>This first strategy, implemented by the Alpine F1 Team consists of the flap, made of the second and third element, rotating downwards of <span class="math inline">\(\approx30^\circ\)</span> about a point at the leading edge of the second element:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_18/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The simulated geometry of Alpine style SLM</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/alpine-rear-drs.jpg" class="img-fluid figure-img"></p>
<figcaption>Alpine’s own implementation</figcaption>
</figure>
</div>
</div>
<p>Due to the presence of the slot gap this strategy is limited, in the rotation angle, by the fact that the rotated second element should not intersect the mainplane, which would result in a disruptive failure:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_18/yNormalProfiles_y00.45.png" class="img-fluid figure-img"></p>
<figcaption>A slice of the mesh close to the wingtip, showing the reduced slot gap between first and second element</figcaption>
</figure>
</div>
<p>The effect of SLM is immediately apparent when looking at <span class="math inline">\(y\)</span>-normal slices. The second element leading edge generates a strong separation on the pressure side, but having such high camber profiles at low incidence reduces greatly the amount of upwash generated by the wing, thus reducing downforce and most importantly drag.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/a8rrdMRqYEA" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>This first strategy for the pivot point of SLM results in <span class="math inline">\(C_D=0.109\)</span>, a 78.2% drag reduction and <span class="math inline">\(C_L=-0.709\)</span>, a 76.0% reduction.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_18/yNormalCpTotLIC_28_yp00.28.png" class="img-fluid figure-img"></p>
<figcaption>A y-normal 2D slice Cp_tot visualization, at the y=0.28 m station</figcaption>
</figure>
</div>
</section>
<section id="regular-style-slm" class="level4" data-number="3.3.3">
<h4 data-number="3.3.3" class="anchored" data-anchor-id="regular-style-slm"><span class="header-section-number">3.3.3</span> 3.3.3 Regular style SLM</h4>
<p>The second strategy is called <em>Regular</em> as it appears on most 2026 cars, and it rotates the second and third element of <span class="math inline">\(\approx32^\circ\)</span> about the third element trailing edge, bringing the second element leading edge gap. This SLM implementation generates a very large gap between the mainplane and the opened flap, as can be seen below:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_19/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The simulated geometry of regular style SLM</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/redbull-slm.png" class="img-fluid figure-img"></p>
<figcaption>Red Bull’s own implementation</figcaption>
</figure>
</div>
</div>
<p>This version of the rear wing generated a drag coefficient of <span class="math inline">\(C_D=0.118\)</span>, down 76.3% w.r.t. corner mode, and a lift coefficient of <span class="math inline">\(C_L=-0.884\)</span>, a 70.7% reduction. The numbers seem to suggest that this strategy is less effective then the Alpine style SLM, but inspection of <span class="math inline">\(y\)</span>-normal slices reveals that the simulated implementation is producing a significant amount of upwash:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/uzA0E4UJsYI" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_19/yNormalCpTotLIC_28_yp00.28.png" class="img-fluid figure-img"></p>
<figcaption>A y-normal 2D slice Cp_tot visualization, at the y=0.28 m station</figcaption>
</figure>
</div>
<p>The heavily cambered flap is pushing the flow upwards, and the second element leading edge separation is not as pronounced as in the previous SLM strategy. All these results suggest that the flaps are producing too much downforce, and thus induced drag, due to the incidence, which is too high. Further lowering the flaps angle of attack should as a consequence prove beneficial.</p>
</section>
<section id="macarena-style-slm" class="level4" data-number="3.3.4">
<h4 data-number="3.3.4" class="anchored" data-anchor-id="macarena-style-slm"><span class="header-section-number">3.3.4</span> 3.3.4 Macarena style SLM</h4>
<p>The third strategy is the most eye-catching innovative aerodynamic concept appeared on the 2026 F1 grid so far. Ferrari presented this in the last day of Bahrain testing, and it involves the second and third element rotating around a point located at about the midpoint of the third element. Instead of rotating of <span class="math inline">\(\approx30^\circ\)</span> the flaps continue their rotation for a total of <span class="math inline">\(\approx210^\circ\)</span>, taking advantage of the 2026 regulations specifying an actuation time for the flap rotation of 0.4 s, enough to rotate by more then the standard amounts. In this way the nominal trailing edge of the wing, i.e.&nbsp;the Gurney flap, becomes a leading edge. This strategy generates an even larger gap between the mainplane and the flaps. Another feature of this design in the absence of the conventional SLM fairing. The actuators are in this case located inside the endplates, and the central fairing pillar is not needed. This novel strategy can be seen in the below images:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_20/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The simulated geometry of Macarena style SLM</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ferrari-macarena.jpg" class="img-fluid figure-img"></p>
<figcaption>Ferrari’s own implementation</figcaption>
</figure>
</div>
</div>
<p>This wing is characterized by a drag coefficient of <span class="math inline">\(C_D=0.089\)</span>, an 82.1% decrease, and a lift coefficient of <span class="math inline">\(C_L=-0.067\)</span>, down 97.7% with respect to corner mode. The results evidently support the effectiveness of this design, as almost all downforce is eliminated and drag is cut down massively. The reason for this behaviour can be seen through the <span class="math inline">\(y\)</span>-normal animation, where the almost complete absence of upwash is noteworthy. The rotated flaps induces downwash on the flow out of the mainplane, thus bringing drag reduction to a minimum. Having no downwash from the mainplane should also help reducing the diffuser expansion more effectively than other strategies, thus cutting down on downforce and drag in another key component. The leading edge separation bubble at the Gurney also seems much smaller due to the relative size of third and second element. As a final observation, perhaps the rotation is a bit too large, and reducing it by a couple of degrees can make the upwash even less significant.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/uN6atGhySmM" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_20/yNormalCpTotLIC_28_yp00.28.png" class="img-fluid figure-img"></p>
<figcaption>A y-normal 2D slice Cp_tot visualization, at the y=0.28 m station</figcaption>
</figure>
</div>
<p>A few notes must made regarding specifically the Macarena style CFD simulation:</p>
<ul>
<li>The utilized CAD geometry did not have a proper bulge in the endplate to simulate the SLM actuators</li>
<li>Ferrari had introduced another interesting device in the same Bahrain testing: an exhaust pipe winglet. This geometry is generating upwash of exhaust gases, and certainly interacting with the downwash caused by the upside down flaps. For this reason the complex interaction of this SLM strategy cannot be predicted with certainty, and performance benefits can be easily under or over estimated</li>
</ul>
<p>Nonetheless this CFD analysis seems to indicate that the avenue of an upside-down flap for SLM is promising and is worthy of consideration, also explaining Ferrari interest in testing it multiple times to get the mechanism to properly work for races usage.</p>
</section>
<section id="optimized-regular-style-slm" class="level4" data-number="3.3.5">
<h4 data-number="3.3.5" class="anchored" data-anchor-id="optimized-regular-style-slm"><span class="header-section-number">3.3.5</span> 3.3.5 Optimized regular style SLM</h4>
<p>The fourth and final strategy is a revised regular style SLM. Since Macarena SLM produced very promising results it was deemed interesting to compare it to the most common SLM implementation, when the latter is optimized for better drag reduction. More specifically the optimization involved a rotation of <span class="math inline">\(\approx37^\circ\)</span>, more than the previous version. This makes the whole wing more similar to the SLM brought by McLaren on this year’s car, as can be seen:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_21/Geometry_TopLeft.png" class="img-fluid figure-img"></p>
<figcaption>The simulated geometry of the optimized regular style SLM</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/mclaren-slm.png" class="img-fluid figure-img"></p>
<figcaption>McLaren’s own implementation</figcaption>
</figure>
</div>
</div>
<p>As can be seen by moving in the spanwise direction the separation bubble is much larger, and as a consequence upwash is almost nonexistent. The downside is slightly thicker wake when compared to the Macarena strategy. This is reflected in the results, with a drag coefficient of <span class="math inline">\(C_D=0.092\)</span>, still higher than Macarena, and a lift coefficient of <span class="math inline">\(C_L=-0.348\)</span>, confirming that the mainplane is still working similarly to the nominal corner mode.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/1h0N1jeonCI" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_21/yNormalCpTotLIC_28_yp00.28.png" class="img-fluid figure-img"></p>
<figcaption>A y-normal 2D slice Cp_tot visualization, at the y=0.28 m station</figcaption>
</figure>
</div>
<p>A final comment comparing Macarena and optimized regular style SLM can be made by analyzing the following pictures:</p>
<div class="{.layout-ncol=&quot;2&quot;}">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_20/yNormalCp_20_yp00.20.png" class="img-fluid figure-img"></p>
<figcaption>Pressure distribution comparison. Left: Macarena SLM</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/ID_21/yNormalCp_20_yp00.20.png" class="img-fluid figure-img"></p>
<figcaption>Right: Optimized regular SLM</figcaption>
</figure>
</div>
</div>
<p>The regular style wing, having the flap positioned much closer to the first element in the horizontal direction (due to the kinematics of the rotation), generates more high pressure on the pressure side of the wing. Also the suction side of the mainplane seems to work more effectively, thus increasing downforce and drag. The rearward shift in the flap position using Macarena SLM can thus be interpreted as a further advantage of this setup.</p>
</section>
<section id="slm-results-conclusions" class="level4" data-number="3.3.6">
<h4 data-number="3.3.6" class="anchored" data-anchor-id="slm-results-conclusions"><span class="header-section-number">3.3.6</span> 3.3.6 SLM Results &amp; Conclusions</h4>
<p>The following table summarizes the aerodynamic coefficients for the SLM configurations. Notice that all rows regarding <span class="math inline">\(C_L\)</span> are red, as a downforce reduction is in theory a downside. Nonetheless in SLM the most important quantity is drag and drag reduction, as the 2026 generation of cars is characterized by lower energy delivered by the power unit on a per lap basis<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> As a consequence, an efficient straight-line mode is critical: failing to reduce drag adequately at high speed will result in a straight-line speed deficit, exposing the car to overtakes on the main straights.</p>
<p><strong>Table 6: Aerodynamic coefficients for different SLM configurations, percentage deltas are relative to the final rear wing design in corner mode</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Case</th>
<th style="text-align: left;"><span class="math inline">\(C_{D}^{mean}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(C_{L}^{mean}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(L/D\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alpine style</td>
<td style="text-align: left;">0.1086 (-78.2%)</td>
<td style="text-align: left;">-0.7087 (-76.0%)</td>
<td style="text-align: left;">-6.53 (+10.4%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Regular style</td>
<td style="text-align: left;">0.1184 (-76.3%)</td>
<td style="text-align: left;">-0.8841 (-70.0%)</td>
<td style="text-align: left;">-7.47 (+26.3%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Macarena style</td>
<td style="text-align: left;">0.0892 (-82.1%)</td>
<td style="text-align: left;">-0.0665 (-97.7%)</td>
<td style="text-align: left;">-0.75 (-87.4%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Optimized regular style</td>
<td style="text-align: left;">0.0918 (-81.6%)</td>
<td style="text-align: left;">-0.3482 (-88.2%)</td>
<td style="text-align: left;">-3.79 (-35.8%)</td>
</tr>
</tbody>
</table>
</div>
<p>While many details can still be investigated and simulated with higher accuracy the results of this research support some trends found looking at the 2026 F1 cars:</p>
<ul>
<li>the regular style SLM, more similar to the old DRS mechanism is perhaps the easiest to conceive and to design in order to obtain large amounts of drag reduction</li>
<li>Alpine style SLM seems to necessitate a very collaborative mainplane design, considering the disadvantage of having the rotation angle limited</li>
<li>the Macarana style SLM probably offers the most potential to be exploited, though careful interaction with other elements of the car is required and is complex from a mechanical point of view</li>
</ul>
</section>
</section>
<section id="a-final-discussion-on-grid-convergence" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="a-final-discussion-on-grid-convergence"><span class="header-section-number">3.4</span> 3.4 A Final Discussion on Grid Convergence</h3>
<p>As the previous discussion made clear, obtaining proper grid convergence on a personal laptop was impossible, and simulation time was extremely long even for this simplified simulation running for a small amount of pseudo-time iterations, taking more than 10 hours per case. Considering also the time required to adjust the geometry and smooth out possible issues arising in the meshing procedure the time required ballooned pretty quickly. While not initially considered when developing and simulating the geometry, during later stages of the work the investigated solution was AWS, a cloud computing platform offered by Amazon, which offers tight CLI integration and many choices of compute instances to run extremely large simulations rapidly. By going though cloud computing it was possible to simulate the same geometry on a much finer mesh, with the goal of verifying grid convergence.</p>
<section id="aws-setup" class="level4" data-number="3.4.1">
<h4 data-number="3.4.1" class="anchored" data-anchor-id="aws-setup"><span class="header-section-number">3.4.1</span> 3.4.1 AWS Setup</h4>
<p>The advantage of using AWS is that the options for compute instances allowed the simulation pipeline to be kept almost identical to the one used on the local PC. After creating an AWS account and installing AWS CLI it was possible to establish an SSH connection to an EC2 compute node chosen accurately for its performance and compatibility. AWS also offers S3 as a storage option, which allowed rapid upload and download of simulation data to and from the personal computer. After an SSH connection was active it was only a matter of installing all required software (i.e.&nbsp;<code>OpenFOAM</code>, <code>Paraview</code> and its dependencies, <code>ffmpeg</code> and <code>marp</code>) and running the bash scripts.</p>
<p>The selection of the <code>m7i.48xlarge</code> instance was dictated by the high memory bandwidth and computational density required for large-scale CFD solvers like OpenFOAM. Featuring 192 vCPUs and 768 GiB of RAM, this instance leverages the 4th Generation Intel Xeon Scalable (Sapphire Rapids) architecture, which introduces DDR5 memory. The transition to DDR5 is critical for fluid dynamics simulations, as these workloads are frequently memory-bound; the increased bandwidth ensures that the large number of cores remains productive without being throttled by data retrieval latency.</p>
</section>
<section id="running-on-aws" class="level4" data-number="3.4.2">
<h4 data-number="3.4.2" class="anchored" data-anchor-id="running-on-aws"><span class="header-section-number">3.4.2</span> 3.4.2 Running on AWS</h4>
<p>AWS was actually used to simulate the last 8 design iterations of corner mode, and all 4 options for SLM. Keeping the same mesh setup, in order to have results comparable to the ones obtained with the personal laptop, every simulation (pre-processing, running and post-processing) required less then 30 minutes. The huge instance is certainly not optimized for a mesh with less then 10 million cells, but the timed saved using cloud computing was still immense, more than 95%.</p>
</section>
<section id="grid-convergence-index-analysis" class="level4" data-number="3.4.3">
<h4 data-number="3.4.3" class="anchored" data-anchor-id="grid-convergence-index-analysis"><span class="header-section-number">3.4.3</span> 3.4.3 Grid Convergence Index Analysis</h4>
<p>Once a suitable AWS setup was found, it was possible to increase the mesh refinement and simulate to do a more proper grid convergence verification. It was decided that the final corner mode geometry would be used for this analysis, in order to verify the results for a design that was deemed sufficiently refined. The mesh specifications can be found in the table below:</p>
<p><strong>Table 7: Mesh configuration summary for convergence study (AWS)</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Coarse</th>
<th style="text-align: left;">Medium</th>
<th style="text-align: left;">Fine</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Number of cells</td>
<td style="text-align: left;">1,541,066</td>
<td style="text-align: left;">10,280,664</td>
<td style="text-align: left;">33,678,514</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cell size (1st refinement box)</td>
<td style="text-align: left;">0.08</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">0.006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cell size (2nd refinement box)</td>
<td style="text-align: left;">0.15</td>
<td style="text-align: left;">0.05</td>
<td style="text-align: left;">0.015</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cell size (wing surface)</td>
<td style="text-align: left;">0.035</td>
<td style="text-align: left;">0.0035</td>
<td style="text-align: left;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cell size (sharp edge refinement)</td>
<td style="text-align: left;">0.0017</td>
<td style="text-align: left;">0.0013</td>
<td style="text-align: left;">0.0011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prismatic layers number</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1st prismatic layer max. thickness</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.008</td>
</tr>
</tbody>
</table>
</div>
<p>The fine mesh is considerably larger, which is promising for a proper GCI study. The results found with these new meshes are:</p>
<p><strong>Table 8: Aerodynamic coefficients for mesh convergence study (AWS)</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Mesh Level</th>
<th style="text-align: left;"><strong><span class="math inline">\(C_{D,mean}\)</span></strong></th>
<th style="text-align: left;"><strong><span class="math inline">\(C_{L,mean}\)</span></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Coarse</td>
<td style="text-align: left;">0.5440</td>
<td style="text-align: left;">-2.9876</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medium</td>
<td style="text-align: left;">0.4992</td>
<td style="text-align: left;">-2.9500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fine</td>
<td style="text-align: left;">0.4941</td>
<td style="text-align: left;">-2.9382</td>
</tr>
</tbody>
</table>
</div>
<p>With these new finer meshes both <span class="math inline">\(C_L\)</span> and <span class="math inline">\(C_D\)</span> exhibit monotonic convergence, with convergence ratios of <span class="math inline">\(CR=0.313\)</span> and <span class="math inline">\(CR=0.153\)</span> respectively, confirming good mesh separation between coarse, medium and fine. The estimated order of convergence is <span class="math inline">\(p=1.41\)</span> for <span class="math inline">\(C_L\)</span> and <span class="math inline">\(p=2.50\)</span> for <span class="math inline">\(C_D\)</span>, the latter being close to the theoretical second-order accuracy of the numerical scheme used. The asymptotic range indicators are <span class="math inline">\(AR=0.946\)</span> for <span class="math inline">\(C_L\)</span> and <span class="math inline">\(AR=1.048\)</span> for <span class="math inline">\(C_D\)</span>, both close to unity, suggesting that the solution is extremely close to the asymptotic regime. The GCI values for the finest mesh pair are below <span class="math inline">\(1.1\%\)</span> for both quantities, well within the accepted threshold for integral aerodynamic coefficients. The results are summarised in the next table.</p>
<p><strong>Table 9: Grid Convergence Index results for the final rear wing geometry</strong></p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Indicator</th>
<th style="text-align: left;"><span class="math inline">\(CR\)</span></th>
<th style="text-align: left;"><span class="math inline">\(p\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\phi_{expected}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(GCI_{32}\)</span> %</th>
<th style="text-align: left;"><span class="math inline">\(GCI_{21}\)</span> %</th>
<th style="text-align: left;"><span class="math inline">\(AR\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(C_L\)</span></td>
<td style="text-align: left;">0.313</td>
<td style="text-align: left;">1.41</td>
<td style="text-align: left;">-2.9224</td>
<td style="text-align: left;">1.110</td>
<td style="text-align: left;">0.672</td>
<td style="text-align: left;">0.946</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(C_D\)</span></td>
<td style="text-align: left;">0.153</td>
<td style="text-align: left;">2.50</td>
<td style="text-align: left;">0.4868</td>
<td style="text-align: left;">2.981</td>
<td style="text-align: left;">1.057</td>
<td style="text-align: left;">1.048</td>
</tr>
</tbody>
</table>
</div>
<p>The GCI study results are this time successful, proving that the final mesh has almost achieved complete grid independence. Since the results for integral coefficient obtained with the medium mesh, which is the one used for the entirety of the results discussed before, are very close the the ones obtained with the fine mesh, it is possible to assume that the design trends found with the medium mesh would still hold for a finer mesh, and thus be applied to reality. More specifically the medium mesh was found to have a 0.4% <span class="math inline">\(C_L\)</span> overestimation, and a 1.0% drag overestimation, well within acceptable bounds.</p>
</section>
</section>
</section>
<section id="conclusions" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">4</span> 4. Conclusions</h2>
<p>This CFD optimization campaign for the 2026 F1 rear wing has successfully demonstrated both the capabilities and the limitations of RANS-based incompressible simulation as a design tool for highly loaded multi-element wings. Starting from an initial geometry with several recognized aerodynamic deficiencies, a systematic development process produced a final corner mode configuration achieving a lift coefficient of <span class="math inline">\(C_L = -2.950\)</span> and a drag coefficient of <span class="math inline">\(C_D = 0.499\)</span>, representing improvements of 24.5% and 15.8% respectively over the baseline design.</p>
<p>Several key aerodynamic lessons were established through this process. Streamlined pylons with appropriate airfoil cross-sections proved critical in eliminating wake-generating separation structures at no meaningful cost to downforce. Leading edge alignment with the local flow direction, particularly for the first element, was shown to suppress suction-side separation and reduce the pressure drag penalty associated with thick wakes. Slot gap optimization between the first and second elements proved to have a considerable influence on efficiency while leaving downforce essentially unchanged. Endplate design was found to be deeply coupled to profile performance: when correctly shaped, the endplate generates an internal expansion that actively contributes to suction beneath the wing rather than passively containing the flow.</p>
<p>The Straight Line Mode investigation revealed a clear hierarchy among the evaluated strategies. The Macarena-style SLM, featuring a <span class="math inline">\(\approx210^\circ\)</span> rotation that inverts the flap orientation, produced by far the most effective drag reduction at 82.1%, while simultaneously reducing downforce by 97.7%, consistent with its observed behaviour on the 2026 Ferrari. The optimized regular-style SLM offered a competitive 81.6% drag reduction with a more moderate downforce loss. The Alpine-style strategy, constrained by the limited rotation angle permitted by the slot gap geometry, proved less flexible and produced the least drag reduction of the four options.</p>
<p>The grid convergence analysis, made possible by AWS EC2 cloud infrastructure, confirmed that the medium mesh used throughout the design campaign introduces errors of approximately 0.4% in <span class="math inline">\(C_L\)</span> and 1.0% in <span class="math inline">\(C_D\)</span> relative to the asymptotically converged solution, both well within acceptable bounds for comparative aerodynamic studies. The GCI values below 1.1% for the finest mesh pair validate the numerical framework and suggest that the design trends identified are reliable, even if the absolute values carry the known uncertainties of wall-function RANS modelling.</p>
<p>Finally future work should focus on the following areas: * low-<span class="math inline">\(Re\)</span> simulation using a refined near-wall mesh targeting <span class="math inline">\(y^+ \approx 1\)</span> would allow direct comparison with the wall-function approach and quantify the associated modelling error on predicted separation * The inclusion of the SLM fairing and bracket geometry would improve the realism of the straight-line mode results and allow a more meaningful aerodynamic evaluation of the Macarena strategy in particular * An aeromap study, spanning a range of pitch, roll and yaw attitudes, would be a necessary step towards understanding real on-track performance, where suspension compliance and ride height variation modify the effective angles of attack * Finally, extending the simulation to a half-car or full-car geometry would capture the interaction between the rear wing, the diffuser, and the rear suspension, which constitutes a major source of additional downforce in modern F1 car design</p>
<hr>
</section>
<section id="acknowledgements" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="acknowledgements"><span class="header-section-number">5</span> Acknowledgements</h2>
<p>16 out of the 24 simulations were performed using OpenFOAM on AWS EC2 infrastructure. Geometry generation was conducted using the OnShape CAD toolkit.</p>
<div style="display: flex; justify-content: center; gap: 15px; margin-top: 40px; margin-bottom: 40px; flex-wrap: wrap;">
<p><a href="assets/Modern_F1_2026_Rear_Wing_Report.pdf" class="btn btn-primary btn-lg" download=""> <i class="bi bi-file-earmark-pdf"></i> Download Full PDF Report </a></p>
<p><a href="mailto:michele.andreozzi@protonmail.com?subject=Inquiry%20regarding%20F1%20CFD%20Portfolio" class="btn btn-outline-primary btn-lg"> <i class="bi bi-envelope"></i> Contact Me </a></p>
</div>
<hr>
</section>
<section id="appendix-code-automation-example" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="appendix-code-automation-example"><span class="header-section-number">6</span> Appendix: Code Automation Example</h2>
<p>Below is the sample Bash script used to fully automate the meshing, run, and post-processing loop (<code>Allrun</code>):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#!/bin/sh</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> <span class="st">"</span><span class="va">${0</span><span class="op">%</span>/<span class="pp">*</span><span class="va">}</span><span class="st">"</span> <span class="kw">||</span> <span class="bu">exit</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="bu">.</span> <span class="va">${WM_PROJECT_DIR</span><span class="op">:?</span><span class="va">}</span>/bin/tools/RunFunctions</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#----------------------------------------------------------------</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="va">decompDict</span><span class="op">=</span><span class="st">"-decomposeParDict system/decomposeParDict"</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize target values</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="va">targetXMin</span><span class="op">=</span>0<span class="kw">;</span> <span class="va">targetXMax</span><span class="op">=</span>0<span class="kw">;</span> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="va">targetYMin</span><span class="op">=</span>0<span class="kw">;</span> <span class="va">targetYMax</span><span class="op">=</span>0<span class="kw">;</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="va">targetZMin</span><span class="op">=</span>0<span class="kw">;</span> <span class="va">targetZMax</span><span class="op">=</span>0<span class="kw">;</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the desired coordinates from the file</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">[</span> <span class="ot">-f</span> <span class="st">"system/boundingBox"</span> <span class="bu">]</span><span class="kw">;</span> <span class="cf">then</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> <span class="bu">read</span> <span class="at">-r</span> <span class="va">key</span> <span class="va">value</span><span class="kw">;</span> <span class="cf">do</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>        <span class="va">clean_value</span><span class="op">=</span><span class="va">${value</span><span class="op">%</span>;<span class="va">}</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">case</span> <span class="st">"</span><span class="va">$key</span><span class="st">"</span> <span class="kw">in</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>            <span class="ss">xNeg</span><span class="kw">)</span> <span class="va">targetXMin</span><span class="op">=</span><span class="st">"</span><span class="va">$clean_value</span><span class="st">"</span> <span class="cf">;;</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>            <span class="ss">xPos</span><span class="kw">)</span> <span class="va">targetXMax</span><span class="op">=</span><span class="st">"</span><span class="va">$clean_value</span><span class="st">"</span> <span class="cf">;;</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>            <span class="ss">yNeg</span><span class="kw">)</span> <span class="va">targetYMin</span><span class="op">=</span><span class="st">"</span><span class="va">$clean_value</span><span class="st">"</span> <span class="cf">;;</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>            <span class="ss">yPos</span><span class="kw">)</span> <span class="va">targetYMax</span><span class="op">=</span><span class="st">"</span><span class="va">$clean_value</span><span class="st">"</span> <span class="cf">;;</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>            <span class="ss">zNeg</span><span class="kw">)</span> <span class="va">targetZMin</span><span class="op">=</span><span class="st">"</span><span class="va">$clean_value</span><span class="st">"</span> <span class="cf">;;</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>            <span class="ss">zPos</span><span class="kw">)</span> <span class="va">targetZMax</span><span class="op">=</span><span class="st">"</span><span class="va">$clean_value</span><span class="st">"</span> <span class="cf">;;</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">esac</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">done</span> <span class="op">&lt;</span> <span class="st">"system/boundingBox"</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="bu">echo</span> <span class="st">"Error: system/boundingBox not found."</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="bu">exit</span> 1</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="cf">fi</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"Target Bounding Box Coordinates: x: [</span><span class="va">$targetXMin</span><span class="st">, </span><span class="va">$targetXMax</span><span class="st">]; y: [</span><span class="va">$targetYMin</span><span class="st">, </span><span class="va">$targetYMax</span><span class="st">]; z: [</span><span class="va">$targetZMin</span><span class="st">, </span><span class="va">$targetZMax</span><span class="st">]"</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="va">offsets</span><span class="op">=</span><span class="va">$(</span><span class="ex">surfaceCheck</span> constant/triSurface/rearWing.stl <span class="kw">|</span> <span class="fu">grep</span> <span class="st">"Bounding Box"</span> <span class="kw">|</span> <span class="fu">awk</span> <span class="at">-v</span> tXmin=<span class="st">"</span><span class="va">$targetXMin</span><span class="st">"</span> <span class="at">-v</span> tXmax=<span class="st">"</span><span class="va">$targetXMax</span><span class="st">"</span> <span class="at">-v</span> tYmin=<span class="st">"</span><span class="va">$targetYMin</span><span class="st">"</span> <span class="at">-v</span> tYmax=<span class="st">"</span><span class="va">$targetYMax</span><span class="st">"</span> <span class="at">-v</span> tZmin=<span class="st">"</span><span class="va">$targetZMin</span><span class="st">"</span> <span class="at">-v</span> tZmax=<span class="st">"</span><span class="va">$targetZMax</span><span class="st">"</span> <span class="st">'</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="st">function snap(v) {</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="st">    # If absolute value is less than 1e-9, return 0; otherwise return the value</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="st">    return (v &lt; 1e-9 &amp;&amp; v &gt; -1e-9) ? 0 : v</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="st">}</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="st">{</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="st">    gsub(/Bounding Box :/, "");</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="st">    gsub(/[()]/, "");</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="st">    </span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="st">    # $1=minX, $2=minY, $3=minZ, $4=maxX, $5=maxY, $6=maxZ</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="st">    # Calculate Raw Margins</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="st">    raw_mXn = $1 - tXmin</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="st">    raw_mXp = tXmax - $4</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="st">    raw_mYn = $2 - tYmin</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="st">    raw_mYp = tYmax - $5</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="st">    raw_mZn = $3 - tZmin</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="st">    raw_mZp = tZmax - $6</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="st">    # Apply Snap to Zero and Print</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="st">    print snap(raw_mXn), snap(raw_mXp), snap(raw_mYn), snap(raw_mYp), snap(raw_mZn), snap(raw_mZp)</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="st">}'</span><span class="va">)</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign the cleaned values</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="bu">set</span> <span class="at">--</span> <span class="va">$offsets</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="va">offXNeg</span><span class="op">=</span><span class="va">$1</span><span class="kw">;</span> <span class="va">offXPos</span><span class="op">=</span><span class="va">$2</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="va">offYNeg</span><span class="op">=</span><span class="va">$3</span><span class="kw">;</span> <span class="va">offYPos</span><span class="op">=</span><span class="va">$4</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="va">offZNeg</span><span class="op">=</span><span class="va">$5</span><span class="kw">;</span> <span class="va">offZPos</span><span class="op">=</span><span class="va">$6</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"Calculated Offsets (Filtered): </span><span class="va">$offXNeg</span><span class="st"> </span><span class="va">$offXPos</span><span class="st"> </span><span class="va">$offYNeg</span><span class="st"> </span><span class="va">$offYPos</span><span class="st"> </span><span class="va">$offZNeg</span><span class="st"> </span><span class="va">$offZPos</span><span class="st">"</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a> <span class="co"># Start the meshing process</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> surfaceFeatureEdges constant/triSurface/rearWing.stl constant/triSurface/rearWing.fms <span class="at">-angle</span> 2</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> FMSToSurface constant/triSurface/rearWing.fms constant/triSurface/rearWing.vtk <span class="at">-exportFeatureEdges</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> surfaceGenerateBoundingBox constant/triSurface/rearWing.fms constant/triSurface/masterGeometry.stl <span class="va">$offXNeg</span> <span class="va">$offXPos</span> <span class="va">$offYNeg</span> <span class="va">$offYPos</span> <span class="va">$offZNeg</span> <span class="va">$offZPos</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> cartesianMesh</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> improveSymmetryPlanes</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> improveMeshQuality</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> topoSet</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> checkMesh <span class="at">-writeAllFields</span> <span class="at">-constant</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="fu">touch</span> <span class="st">"</span><span class="va">$(</span><span class="fu">basename</span> <span class="st">"</span><span class="va">$PWD</span><span class="st">"</span><span class="va">)</span><span class="st">.foam"</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Paraview automation</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"Running Paraview to extract images"</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="ex">/home/michele/Codes/ParaView-6.0.1-MPI-Linux-Python3.12-x86_64/bin/pvpython</span> meshPostProcessing.py <span class="op">&gt;</span> log.meshPostProcessing</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> <span class="va">$decompDict</span> decomposePar</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="co">#- Set the initial fields for parallel running</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="ex">restore0Dir</span> <span class="at">-processor</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="ex">runParallel</span> <span class="va">$decompDict</span> patchSummary</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="ex">runParallel</span> <span class="va">$decompDict</span> potentialFoam <span class="at">-writephi</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="ex">runParallel</span> <span class="va">$decompDict</span> <span class="va">$(</span><span class="ex">getApplication</span><span class="va">)</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="ex">runApplication</span> reconstructPar <span class="at">-latestTime</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="ex">simpleFoam</span> <span class="at">-postProcess</span> <span class="at">-dict</span> system/postProcessDict <span class="at">-latestTime</span> <span class="op">&gt;</span> log.postProcess</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">touch</span> <span class="st">"</span><span class="va">$(</span><span class="fu">basename</span> <span class="st">"</span><span class="va">$PWD</span><span class="st">"</span><span class="va">)</span><span class="st">.foam"</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="co">#----------------------------------------------------------------</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a><span class="co"># Paraview automation</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"Running Paraview to extract 3D images"</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="ex">/home/michele/Codes/ParaView-6.0.1-MPI-Linux-Python3.12-x86_64/bin/pvbatch</span> results3DPostProcessing.py <span class="op">&gt;</span> log.results3DPostProcessing</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"Running Paraview to extract 2D images"</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="ex">/home/michele/Codes/ParaView-6.0.1-MPI-Linux-Python3.12-x86_64/bin/pvbatch</span> results2DPostProcessing.py <span class="op">&gt;</span> log.results2DPostProcessing</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"Running Paraview to extract plots"</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="ex">/home/michele/Codes/ParaView-6.0.1-MPI-Linux-Python3.12-x86_64/bin/pvpython</span> yPlusPlot.py <span class="op">&gt;</span> log.yPlusPlot</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="ex">/home/michele/Codes/ParaView-6.0.1-MPI-Linux-Python3.12-x86_64/bin/pvpython</span> cpPlot.py <span class="op">&gt;</span> log.cpPlot</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="ex">/home/michele/Codes/ParaView-6.0.1-MPI-Linux-Python3.12-x86_64/bin/pvpython</span> caseSummary.py <span class="op">&gt;</span> log.caseSummary</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> resultPic/2D</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"Generating videos"</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">ls</span> <span class="at">-v</span> xNormalCpTot_<span class="pp">*</span><span class="va">)</span> <span class="kw">|</span> <span class="ex">ffmpeg</span> <span class="at">-f</span> image2pipe <span class="at">-framerate</span> 10 <span class="at">-i</span> <span class="at">-</span> <span class="at">-vf</span> <span class="st">"pad=ceil(iw/2)*2:ceil(ih/2)*2"</span> <span class="at">-c:v</span> libx264 <span class="at">-pix_fmt</span> yuv420p ../xNormalCpTot.mp4</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">ls</span> <span class="at">-v</span> xNormalCpTotLIC_<span class="pp">*</span><span class="va">)</span> <span class="kw">|</span> <span class="ex">ffmpeg</span> <span class="at">-f</span> image2pipe <span class="at">-framerate</span> 10 <span class="at">-i</span> <span class="at">-</span> <span class="at">-vf</span> <span class="st">"pad=ceil(iw/2)*2:ceil(ih/2)*2"</span> <span class="at">-c:v</span> libx264 <span class="at">-pix_fmt</span> yuv420p ../xNormalCpTotLIC.mp4</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">ls</span> <span class="at">-v</span> yNormalCpTot_<span class="pp">*</span><span class="va">)</span> <span class="kw">|</span> <span class="ex">ffmpeg</span> <span class="at">-f</span> image2pipe <span class="at">-framerate</span> 10 <span class="at">-i</span> <span class="at">-</span> <span class="at">-vf</span> <span class="st">"pad=ceil(iw/2)*2:ceil(ih/2)*2"</span> <span class="at">-c:v</span> libx264 <span class="at">-pix_fmt</span> yuv420p ../yNormalCpTot.mp4</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">ls</span> <span class="at">-v</span> yNormalCpTotLIC_<span class="pp">*</span><span class="va">)</span> <span class="kw">|</span> <span class="ex">ffmpeg</span> <span class="at">-f</span> image2pipe <span class="at">-framerate</span> 10 <span class="at">-i</span> <span class="at">-</span> <span class="at">-vf</span> <span class="st">"pad=ceil(iw/2)*2:ceil(ih/2)*2"</span> <span class="at">-c:v</span> libx264 <span class="at">-pix_fmt</span> yuv420p ../yNormalCpTotLIC.mp4</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">ls</span> <span class="at">-v</span> zNormalCpTot_<span class="pp">*</span><span class="va">)</span> <span class="kw">|</span> <span class="ex">ffmpeg</span> <span class="at">-f</span> image2pipe <span class="at">-framerate</span> 10 <span class="at">-i</span> <span class="at">-</span> <span class="at">-vf</span> <span class="st">"pad=ceil(iw/2)*2:ceil(ih/2)*2"</span> <span class="at">-c:v</span> libx264 <span class="at">-pix_fmt</span> yuv420p ../zNormalCpTot.mp4</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$(</span><span class="fu">ls</span> <span class="at">-v</span> zNormalCpTotLIC_<span class="pp">*</span><span class="va">)</span> <span class="kw">|</span> <span class="ex">ffmpeg</span> <span class="at">-f</span> image2pipe <span class="at">-framerate</span> 10 <span class="at">-i</span> <span class="at">-</span> <span class="at">-vf</span> <span class="st">"pad=ceil(iw/2)*2:ceil(ih/2)*2"</span> <span class="at">-c:v</span> libx264 <span class="at">-pix_fmt</span> yuv420p ../zNormalCpTotLIC.mp4</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ../..</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="fu">cp</span> <span class="at">-f</span> ../casesSummary.csv ../casesSummaryBackup.csv</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="co">#----------------------------------------------------------------</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert report into a simple pdf</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> postProcessing/foamReport/500</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="ex">marp</span> foamReport.md <span class="at">--allow-local-files</span> <span class="at">--pdf</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The development of profiles was in the end considered of interest for the author.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>It was actually surprising how much quicker the meshing process was compared to snappyHexMesh.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>A similar behaviour can be found in the same image close to the trailing edge of the first element on the suction side.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The python script converting the Paraview-extracted data into readable plots was intended to automatically detect the wing elements, split the data and assign a label and color to each. While the splitting works fine as shown, the labels and colors seems to sometime switch the order of the profiles. This was considered a minor issue and never solver in the end (at the time of writing at the very least).<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>With a human sanity check of the integral quantities plots still being executed after each simulation.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>This is clearly a fallible methodology, not suggested for any industrial or professional CFD study, nonetheless it was found to be the only viable solution.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>As described, convergence plots are also generated by the scripts, allowing a further verification of iteration convergence.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Wall shear stress is an indicator of surface friction, and low wall shear stress areas indicate weak flow and potential separation, or even detached flow.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p><span class="math inline">\(C_p\)</span> is the most common indicator of static pressure, used to evaluate local loading. <span class="math inline">\(C_p^{tot}\)</span> is instead a measure of the energy in the air (it indicates well where non-isoentropic processes, such as viscosity, have taken place, reducing the sum of static and dynamic pressure). <span class="math inline">\(C_p^{tot}\)</span> is of paramount importance to understand where to extract performance, and where to divert dirty air.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>LIC visualization is very common in aerodynamic development as it allows the immediate determination of the flow direction. In this way by looking at, e.g., <span class="math inline">\(C_p^{tot}\)</span> with LIC one can understand how much potential to be extracted a certain region has, and where this <em>local energy</em> is headed to.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>As the comment regarding the mesh should point out, the grid at this point is probably not fine enough to resolve the flow features exactly, nonetheless it should hopefully help at improving basic issues in the geometry.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>It is actually interesting to notice that thin airfoil theory, an analytic model developed back in the 1920s by Munk and Glauert, proved that the maximum effect of camber on lift is found at the trailing edge.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>More specifically the 3D splines were redesigned as the intersection of a couple of planar spline views, allowing better local control.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Although probably optimization could reduce the amount of induced drag caused by vorticity released in the wake.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>A side effect of thin profiles is that they need to be well aligned with the flow, as the sharp leading edge can easily cause separation. This in turn means that aerodynamics must be studied at a series of attitudes, for different yaw, pitch and roll angles. These angles are a function of stiffnesses in the suspension setup, thus CFD alone cannot provide the full picture of the aerodynamic performance. A well developed aeromap is a collaboration between car dynamics and aerodynamics.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>This is due to the reliance on larger electric batteries, which need more intensive recharging.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/github\.com\/andreozzimichele\/1d23982d-7cc9-46d9-8530-f6d58455ad62");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>